extends SceneTree
## Regenerates res://data/dialogue/dialogue_pool.tres from the rows below.
##
##     godot --headless --path game --script res://tools/build_dialogue.gd
##
## UNLIKE seed_interests.gd and its siblings, this is a BUILD STEP, not a
## bootstrap - it is re-run whenever a line changes, and the .tres it writes
## is an artifact, not the source of truth. Edit dialogue HERE. Anything typed
## into the Inspector is gone on the next run.
##
## The distinction is the same one build_*_scene.gd already draws. Interests,
## cards and archetypes are STRUCTURED data with cross-references a designer
## genuinely tunes in the Inspector - dragging an Interest into top_interests.
## Dialogue is PROSE: nothing to drag, the payload is a sentence, and the file
## will run to hundreds of them. A 200-element array of collapsed sub-resources
## is a bad text editor and a worse diff.

const DIR := "res://data/dialogue"

const KNOWN_TAGS := [&"appeal", &"patience", &"concession", &"pressure",
	&"padding", &"demand_thinking", &"demand_restless", &"demand_manager",
	&"demand_show_me", &"demand_better_quote", &"relief", &"ignored",
	&"accepted", &"impatient",
	# Objections - see ProductCardDef.objection_tags and Shift._object(). The
	# warm word instead, when a product already clears their Line.
	&"objection", &"objection_walkaway", &"objection_walkaway_gap", &"interested",
	# Their answers to the method's techniques - the reskinned appeal cards.
	&"reply_empathize", &"reply_clarify", &"reply_relate", &"reply_value",
	&"reply_budget", &"reply_listen",
	# Yours - see CardDef.player_dialogue_tags. player_close is the trial
	# close offer() says itself.
	&"player_pitch", &"player_smalltalk", &"player_empathize",
	&"player_budget", &"player_value", &"player_fearmonger",
	&"player_relate", &"player_clarify", &"player_pad", &"player_listen",
	&"player_guide", &"player_comp", &"player_justthething",
	&"player_rightword", &"player_smile", &"player_jazz", &"player_close"]

## Every objection a customer can be working through. The walkaway_ ones are
## the deck's ("Handling Objections", WALKAWAY Webinar Series 4), condensed;
## the bare ones are everybody else's. savings and line_of_credit are never
## raised outright - asking "how would you make the payments?" flushes them out.
const KNOWN_OBJECTIONS := [
	&"walkaway_too_expensive", &"walkaway_no_thanks", &"walkaway_dont_need",
	&"walkaway_savings", &"walkaway_line_of_credit", &"walkaway_work_coverage",
	&"walkaway_lots_of_insurance", &"walkaway_wont_qualify",
	&"walkaway_buy_outright",
	&"walkaway_gap_too_expensive", &"walkaway_gap_insured",
	&"walkaway_gap_dont_need", &"walkaway_gap_no_thanks",
	&"too_expensive", &"dont_need", &"no_thanks"]

const DESIGN_RULE := "One library, divided by TAG, not by file. A line's tags say which pool it belongs to and are the only required match; archetype_ids, product_ids, appeal_bands and objection_ids are optional narrowings, and an empty one means any. Narrowing is additive and exclusive: a line naming karen is unavailable to everybody else, never merely less likely. Every tag must keep at least one line with NO narrowings at all - that is the fallback that stops a pool going silent, and the suite enforces it. Specific lines are WEIGHTED over generic ones, never substituted for them: one karen line must not make ten generic ones unreachable, or every karen says the same sentence for the rest of the run. The one exception is an open objection: where lines answer it, only they are drawn, because the word track written for it IS the answer. A line's `becomes` opens or moves the customer's objection when it is said. The player_* tags are YOUR lines, asked for by a card's player_dialogue_tags; on those, an archetype narrowing means who you are talking to. GENERATED by tools/build_dialogue.gd - edit the rows there, not this file."

# tags, text, archetype_ids, product_ids, appeal_bands
const LINES := [
	[[&"appeal"], "\"Okay. Keep talking.\"", [], [], []],
	[[&"appeal"], "\"Huh. I had not thought about it that way.\"", [], [], []],
	[[&"appeal"], "\"That is not nothing, I will give you that.\"", [], [], []],
	[[&"appeal"], "\"Alright. I am listening.\"", [], [], []],
	[[&"appeal"], "\"Oh, I've heard of that.\"", [], [], []],

	[[&"appeal"], "\"You are not really selling me here.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"It still feels like a lot for what it is.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"Okay, I can see how that would be helpful.\"", [], [], [&"ALMOST"]],
	[[&"appeal"], "\"Oh, that's pretty good.\"", [], [], [&"ALMOST"]],

	[[&"appeal"], "\"And is that in writing, or just you saying it?\"", [&"karen"], [], []],
	[[&"appeal"], "\"Fine. What is the other guy charging for that?\"", [&"hawk"], [], []],
	[[&"appeal"], "\"Do you have the actual spec sheet on that?\"", [&"tech"], [], []],
	[[&"appeal"], "\"Sure, sure. How much longer is this going to be?\"", [&"kicker"], [], []],
	[[&"appeal"], "\"Let me run that past my partner before I say anything.\"", [&"family"], [], []],

	[[&"appeal"], "\"So if I total it, that is the part that covers me?\"", [], [&"gap"], []],
	[[&"appeal"], "\"And this is on top of the factory warranty?\"", [], [&"vsc"], []],

	[[&"patience"], "\"Hah! The 401 was a parking lot this morning.\"", [], [], []],
	[[&"patience"], "\"No rush on my end. I took the afternoon off.\"", [], [], []],
	[[&"patience"], "\"Oh, no, I got time, no worries.\"", [], [], []],
	[[&"patience"], "\"My daughter has a game later, but we should be fine.\"", [], [], []],
	[[&"patience"], "\"That is nice, but I really do need to go soon.\"", [&"kicker"], [], []],

	[[&"concession"], "\"Now you are speaking my language.\"", [], [], []],
	[[&"concession"], "\"See, that is what I was waiting for.\"", [], [], []],
	[[&"concession"], "\"Better, but it's still not what the place next door quoted.\"", [&"hawk"], [], []],

	[[&"pressure"], "\"Alright, alright. You do not have to lean on me.\"", [], [], []],
	[[&"pressure"], "\"Okay. Fine. Just stop.\"", [], [], []],
	[[&"pressure"], "\"Do not take that tone with me.\"", [&"karen"], [], []],

	[[&"padding"], "\"Sure. That sounds reasonable.\"", [], [], []],
	[[&"padding"], "\"I will take your word on the numbers.\"", [], [], []],

	# Migrated verbatim from CustomerAction.dialogue / Demand.dialogue -
	# nothing that was already spoken changes here, it just moves into the
	# tagged system. Each demand-raise tag keeps exactly one line for now;
	# the point of the migration is that adding a second is now a data edit.
	[[&"demand_thinking"], "\"Could we have a moment?\"", [], [], []],
	[[&"demand_restless"], "\"How long is this going to take?\"", [], [], []],
	[[&"demand_manager"], "\"Is there someone else I can speak to?\"", [], [], []],
	[[&"demand_show_me"], "\"What have you got that is actually worth having?\"", [], [], []],
	[[&"demand_better_quote"], "\"I had another dealer at less than that.\"", [], [], []],
	# Demand.dialogue's own text was never actually spoken anywhere before
	# this migration (dead data - _settle_demand() hardcoded "" always), so
	# it is not "the" line for this tag - it becomes a second, free variant.
	[[&"demand_better_quote"], "\"The place down the street does this for less.\"", [], [], []],

	# New: demand settlement never spoke at all before this migration
	# (_settle_demand() hardcoded dialogue to "" unconditionally). Generic
	# for now - a specific demand can narrow these later the same way any
	# other tag narrows, by adding archetype/product/band filters.
	[[&"relief"], "\"Alright, that works.\"", [], [], []],
	[[&"relief"], "\"Good. That is all I wanted.\"", [], [], []],
	[[&"relief"], "\"Now we are getting somewhere.\"", [], [], []],
	[[&"ignored"], "\"Fine. Forget it.\"", [], [], []],
	[[&"ignored"], "\"Whatever you say.\"", [], [], []],
	[[&"ignored"], "\"That's not nice.\"", [], [], []],

	# Not asked for by any card, action or demand - Shift says these itself.
	# accepted: the moment an offer clears their Line and they take it. Where a
	# line names a product, it is about the one they just took.
	[[&"accepted"], "\"Alright. Put me down for that one.\"", [], [], []],
	[[&"accepted"], "\"Yeah, okay. I can see that being worth it.\"", [], [], []],
	[[&"accepted"], "\"You know what? Sold.\"", [], [], []],
	[[&"accepted"], "\"Good. That is one less thing to worry about.\"", [], [], []],
	[[&"accepted"], "\"Fine, you got me. I will take it.\"", [], [], []],
	[[&"accepted"], "\"Fine. But I want all of that in writing.\"", [&"karen"], [], []],
	[[&"accepted"], "\"At that number? Alright, I can live with it.\"", [&"hawk"], [], []],
	[[&"accepted"], "\"Nice. I will read the fine print tonight.\"", [&"tech"], [], []],
	[[&"accepted"], "\"My partner is going to be glad we got that one.\"", [&"family"], [], []],
	[[&"accepted"], "\"Sure, sure. Throw it on. Are we done?\"", [&"kicker"], [], []],
	[[&"accepted"], "\"Sounds good to me!\"", [&"easygoing"], [], []],
	[[&"accepted"], "\"Yep. Whatever you think is best.\"", [&"laydown"], [], []],
	[[&"accepted"], "\"Good. I am not paying off a car I do not have.\"", [], [&"gap"], []],
	[[&"accepted"], "\"No more surprise repair bills. I like that.\"", [], [&"vsc"], []],
	[[&"accepted"], "\"Given my street? Yes, please.\"", [], [&"theft"], []],
	[[&"accepted"], "\"So my trade-in keeps its value. Smart.\"", [], [&"tvp"], []],
	[[&"accepted"], "\"The wheels on my last car were a mess. Deal.\"", [], [&"appearance"], []],
	[[&"accepted"], "\"If I lose my job, the payments are covered? Done.\"", [], [&"ppp"], []],
	[[&"accepted"], "\"Somebody to call at two in the morning? I will take it.\"", [], [&"concierge"], []],
	[[&"accepted"], "\"A little breathing room on the payments. Good.\"", [], [&"flex"], []],
	[[&"accepted"], "\"Towing and a tune-up? Now you are talking.\"", [], [&"perf"], []],
	[[&"accepted"], "\"I feel so much more confident about this purchase.\"", [], [&"wap"], []],
	[[&"accepted"], "\"Now I'm confident I'll be covered if it's a total loss.\"", [], [&"tlp"], []],

	# impatient: the moment their patience drops to ShiftConfig.impatient_at or
	# under - once per dip, not once per tick spent down there.
	[[&"impatient"], "\"Are we almost done here?\"", [], [], []],
	[[&"impatient"], "\"I really do not have all day.\"", [], [], []],
	[[&"impatient"], "\"Can we speed this up a little?\"", [], [], []],
	[[&"impatient"], "\"I am starting to lose my patience.\"", [], [], []],
	[[&"impatient"], "\"My parking runs out soon, you know.\"", [], [], []],
	[[&"impatient"], "\"I have been sitting here for AGES.\"", [&"karen"], [], []],
	[[&"impatient"], "\"Every minute in this chair is costing me money.\"", [&"hawk"], [], []],
	[[&"impatient"], "\"I could have read the whole manual by now.\"", [&"tech"], [], []],
	[[&"impatient"], "\"The kids are about to lose it back there.\"", [&"family"], [], []],
	[[&"impatient"], "\"Yeah, I think I am just going to go.\"", [&"kicker"], [], []],
	[[&"impatient"], "\"Not to rush you, but I have somewhere to be.\"", [&"easygoing"], [], []],
	[[&"impatient"], "\"Just tell me where to sign, okay?\"", [&"laydown"], [], []],

	# ------------------------------------------------------------- YOURS
	# What you say as you play a card - see CardDef.player_dialogue_tags. An
	# archetype narrowing here is who you are talking to; a product one is the
	# product on the table (for a product card, the one going down). The
	# method's techniques - empathize, clarify, relate, value, budget, listen -
	# are the reskinned appeal cards. What each says to an OPEN objection is in
	# OBJECTIONS below; these rows are what they say to anything else.

	# player_pitch: putting a product in front of them.
	[[&"player_pitch"], "\"Now, have you heard about this one?\"", [], [], []],
	[[&"player_pitch"], "\"Can I show you one more thing? It's quick.\"", [], [], []],
	[[&"player_pitch"], "\"This one is really popular this month.\"", [], [], []],
	[[&"player_pitch"], "\"I'd be doing you a disservice if I skipped this one.\"", [], [], []],
	[[&"player_pitch"], "\"Okay, hear me out on this one.\"", [], [], []],
	[[&"player_pitch"], "\"Most people wish they'd bought this one sooner.\"", [], [], []],
	[[&"player_pitch"], "\"I know, I know. Just hear me out.\"", [], [], [&"COLD"]],
	[[&"player_pitch"], "\"Oh, this one is right up your alley.\"", [], [], [&"ALMOST"]],
	[[&"player_pitch"], "\"With the kids in the back, you'll want this one.\"", [&"family"], [], []],
	[[&"player_pitch"], "\"Before you ask: yes, this one comes with paperwork.\"", [&"karen"], [], []],
	[[&"player_pitch"], "\"And before you ask, nobody else offers this one.\"", [&"hawk"], [], []],
	[[&"player_pitch"], "\"I've got the full terms on this if you want them.\"", [&"tech"], [], []],
	[[&"player_pitch"], "\"Thirty seconds, I promise. Check this out.\"", [&"kicker"], [], []],
	[[&"player_pitch"], "\"You're going to love this one.\"", [&"easygoing"], [], []],
	[[&"player_pitch"], "\"You're going to want this one, trust me.\"", [&"laydown"], [], []],
	[[&"player_pitch"], "\"Let's talk about what happens if the car gets totaled.\"", [], [&"gap"], []],
	[[&"player_pitch"], "\"How long were you planning to keep this car?\"", [], [&"vsc"], []],
	[[&"player_pitch"], "\"Do you park on the street at all?\"", [], [&"theft"], []],
	[[&"player_pitch"], "\"Planning to trade this one in someday?\"", [], [&"tvp"], []],
	[[&"player_pitch"], "\"You want it looking showroom-new for years, right?\"", [], [&"appearance"], []],
	[[&"player_pitch"], "\"How secure would you say your job is? Just curious.\"", [], [&"ppp"], []],
	[[&"player_pitch"], "\"How would you like to never sit in a waiting room again?\"", [], [&"concierge"], []],
	[[&"player_pitch"], "\"Ever had a month where the budget just didn't stretch?\"", [], [&"flex"], []],
	[[&"player_pitch"], "\"Do you ever tow anything? Boat? Trailer? Small house?\"", [], [&"perf"], []],
	[[&"player_pitch"], "\"Let me tell you about our WALKAWAY program.\"", [], [&"wap"], []],
	[[&"player_pitch"], "\"This one pairs really nicely with WALKAWAY.\"", [], [&"tlp"], []],

	[[&"player_smalltalk"], "\"So, how was the drive in? Traffic behave itself?\"", [], [], []],
	[[&"player_smalltalk"], "\"Crazy weather we're having, huh?\"", [], [], []],
	[[&"player_smalltalk"], "\"Any big plans for the weekend?\"", [], [], []],
	[[&"player_smalltalk"], "\"Can I get you a coffee? It's terrible, but it's free.\"", [], [], []],
	[[&"player_smalltalk"], "\"So what do you do for work?\"", [], [], []],
	[[&"player_smalltalk"], "\"Did you catch the game last night?\"", [], [], []],
	[[&"player_smalltalk"], "\"Love the jacket, by the way. Where's it from?\"", [], [], []],
	[[&"player_smalltalk"], "\"Parking okay out there? That lot is a maze.\"", [], [], []],
	[[&"player_smalltalk"], "\"How old are the kids? Mine just started school.\"", [&"family"], [], []],
	[[&"player_smalltalk"], "\"The kids doing okay? There are lollipops at the desk.\"", [&"family"], [], []],
	[[&"player_smalltalk"], "\"Can I get you anything? Water? A manager?\"", [&"karen"], [], []],
	[[&"player_smalltalk"], "\"I'll keep this quick, I promise.\"", [&"kicker"], [], []],
	[[&"player_smalltalk"], "\"You must have done a ton of research on this one.\"", [&"tech"], [], []],
	[[&"player_smalltalk"], "\"Bet you shopped around a bit before coming here, huh?\"", [&"hawk"], [], []],
	[[&"player_smalltalk"], "\"Beautiful day to buy a car, isn't it?\"", [&"easygoing"], [], []],
	[[&"player_smalltalk"], "\"You look like you could use a coffee. Long day?\"", [&"laydown"], [], []],

	# player_empathize: Acknowledge & Empathize (the card that was Explain the
	# Product). Acknowledge the worry; never tell them they're wrong.
	[[&"player_empathize"], "\"I hear you. That's a really fair concern.\"", [], [], []],
	[[&"player_empathize"], "\"Totally understand where you're coming from.\"", [], [], []],
	[[&"player_empathize"], "\"That makes complete sense.\"", [], [], []],
	[[&"player_empathize"], "\"I'd feel the same way in your shoes.\"", [], [], []],
	[[&"player_empathize"], "\"Lots of people feel that way at first.\"", [], [], []],
	[[&"player_empathize"], "\"I'll go slowly. And yes, it's all in writing.\"", [&"karen"], [], []],
	[[&"player_empathize"], "\"I know your time matters. I'll keep it short.\"", [&"kicker"], [], []],
	[[&"player_empathize"], "\"With the kids, I get why every dollar counts.\"", [&"family"], [], []],

	# player_clarify: Ask Clarifying Questions (was Hard Close). Flush out
	# whether it's the cost or the coverage.
	[[&"player_clarify"], "\"What matters most to you in all this?\"", [], [], []],
	[[&"player_clarify"], "\"Can I ask what's giving you pause?\"", [], [], []],
	[[&"player_clarify"], "\"Is it the price, or the coverage itself?\"", [], [], []],
	[[&"player_clarify"], "\"Just so I understand, what's the hesitation?\"", [], [], []],
	[[&"player_clarify"], "\"Quick question, then I'll let you go.\"", [&"kicker"], [], []],
	[[&"player_clarify"], "\"How many years were you planning to keep it?\"", [&"tech"], [], []],

	# player_relate: Keep It Relatable (was Coffee Framing).
	[[&"player_relate"], "\"That's just three cups of coffee a day!\"", [], [], []],
	[[&"player_relate"], "\"Break it down per day and it's pocket change.\"", [], [], []],
	[[&"player_relate"], "\"Skip one latte a week and it pays for itself.\"", [], [], []],
	[[&"player_relate"], "\"That's less than your streaming subscriptions.\"", [], [], []],
	[[&"player_relate"], "\"It's cheaper than a sandwich. A small sandwich.\"", [], [], []],
	[[&"player_relate"], "\"Think of it like a seatbelt for your wallet.\"", [], [], []],
	[[&"player_relate"], "\"It's like a warranty, but for you.\"", [], [], []],
	[[&"player_relate"], "\"Okay, let me try explaining it a different way.\"", [], [], [&"COLD"]],
	[[&"player_relate"], "\"Do the math. Per day, it's basically nothing.\"", [&"hawk"], [], []],

	# player_value: Back to Value (was Bundle It In) - and each product's own
	# value proposition, where one is written for it.
	[[&"player_value"], "\"Since we're already doing the other two...\"", [], [], []],
	[[&"player_value"], "\"Add it to the rest and the payment barely moves.\"", [], [], []],
	[[&"player_value"], "\"You've started the set. Might as well finish it.\"", [], [], []],
	[[&"player_value"], "\"Let me walk you through what this actually covers.\"", [], [], []],
	[[&"player_value"], "\"Here's the short version. No fine print. Well, some.\"", [], [], []],
	[[&"player_value"], "\"It's simple, really. Something goes wrong, you're covered.\"", [], [], []],
	[[&"player_value"], "\"Most people don't know this, but...\"", [], [], []],
	[[&"player_value"], "\"And honestly? It pretty much sells itself.\"", [], [], [&"ALMOST"]],
	[[&"player_value"], "\"One package, and the whole family's covered.\"", [&"family"], [], []],
	[[&"player_value"], "\"I can pull up the full contract if you want the details.\"", [&"tech"], [], []],
	[[&"player_value"], "\"Real quick, the thirty-second version...\"", [&"kicker"], [], []],
	[[&"player_value"], "\"If the car's totaled, GAP pays off what insurance won't.\"", [], [&"gap"], []],
	[[&"player_value"], "\"When the factory warranty ends, this pays the repair bills.\"", [], [&"vsc"], []],
	[[&"player_value"], "\"We etch the glass, track the car, and replace lost keys.\"", [], [&"theft"], []],
	[[&"player_value"], "\"It locks in a floor on your trade-in. No nasty surprises.\"", [], [&"tvp"], []],
	[[&"player_value"], "\"Ceramic coat, tint, wheel care. It stays new for years.\"", [], [&"appearance"], []],
	[[&"player_value"], "\"Lose your job or get hurt, and this makes the payments.\"", [], [&"ppp"], []],
	[[&"player_value"], "\"We pick it up, leave you a loaner, bring it back fixed.\"", [], [&"concierge"], []],
	[[&"player_value"], "\"Skip a payment when money is tight. No questions asked.\"", [], [&"flex"], []],
	[[&"player_value"], "\"Tow package, winter traction, and a badge that says so.\"", [], [&"perf"], []],
	[[&"player_value"], "\"Life happens. WALKAWAY covers the big 'what ifs.'\"", [], [&"wap"], []],
	[[&"player_value"], "\"Fire, theft or a wreck: it covers what the payout misses.\"", [], [&"tlp"], []],

	# player_budget: Budget Options (was Offer a Discount) - "we have different
	# options to suit different budgets."
	[[&"player_budget"], "\"We have options to suit different budgets.\"", [], [], []],
	[[&"player_budget"], "\"There's a lighter plan that still covers the basics.\"", [], [], []],
	[[&"player_budget"], "\"Okay, let me see what I can do here.\"", [], [], []],
	[[&"player_budget"], "\"Tell you what, I'll sharpen my pencil.\"", [], [], []],
	[[&"player_budget"], "\"...but that's the best I can do!\"", [], [], []],
	[[&"player_budget"], "\"Don't tell my manager, but...\"", [], [], []],
	[[&"player_budget"], "\"Alright, how does THIS number look?\"", [], [], [&"COLD"]],
	[[&"player_budget"], "\"Fine, fine. You drive a hard bargain.\"", [&"hawk"], [], []],
	[[&"player_budget"], "\"Since you've been SO patient with me...\"", [&"karen"], [], []],
	[[&"player_budget"], "\"You've been great, so let me knock a bit off.\"", [&"easygoing"], [], []],

	[[&"player_fearmonger"], "\"I had a customer last week who skipped this. Poor guy.\"", [], [], []],
	[[&"player_fearmonger"], "\"You know what a new transmission costs these days?\"", [], [], []],
	[[&"player_fearmonger"], "\"It won't happen to you. That's what my cousin said.\"", [], [], []],
	[[&"player_fearmonger"], "\"Picture it: 2 a.m., side of the highway, no coverage.\"", [], [], []],
	[[&"player_fearmonger"], "\"Nobody plans for the worst day of their life.\"", [], [], []],
	[[&"player_fearmonger"], "\"It's all fun and games until the tow truck shows up.\"", [], [], []],
	[[&"player_fearmonger"], "\"Picture the kids, stuck on the highway at night.\"", [&"family"], [], []],
	[[&"player_fearmonger"], "\"Total it, and you're still paying for it. For years.\"", [], [&"gap"], []],
	[[&"player_fearmonger"], "\"Cars around here vanish overnight. I've seen it.\"", [], [&"theft"], []],
	[[&"player_fearmonger"], "\"One sensor on these costs more than your rent.\"", [], [&"vsc"], []],
	[[&"player_fearmonger"], "\"Nobody expects the layoff. Nobody.\"", [], [&"ppp"], []],
	[[&"player_fearmonger"], "\"One winter of road salt. That's all it takes.\"", [], [&"appearance"], []],

	[[&"player_pad"], "\"There's just a small admin fee on top.\"", [], [], []],
	[[&"player_pad"], "\"That number includes a few little extras.\"", [], [], []],
	[[&"player_pad"], "\"Standard processing. You'll find that everywhere.\"", [], [], []],
	[[&"player_pad"], "\"Let me just tidy these numbers up for you.\"", [], [], []],
	[[&"player_pad"], "\"Don't worry about that line. Everybody pays that.\"", [], [], []],
	[[&"player_pad"], "\"And a little extra here. You won't even notice.\"", [&"laydown"], [], []],

	# player_listen: Active Listening (was Read the Room). Stay calm and
	# curious, and let them talk.
	[[&"player_listen"], "\"Mm-hm. Go on.\"", [], [], []],
	[[&"player_listen"], "\"Tell me more about that.\"", [], [], []],
	[[&"player_listen"], "\"Take your time. I'm listening.\"", [], [], []],
	[[&"player_listen"], "\"So what matters most to you here?\"", [], [], []],
	[[&"player_listen"], "\"What brings you in today, really?\"", [], [], []],
	[[&"player_listen"], "\"Go ahead. I'm all ears. Truly.\"", [&"karen"], [], []],

	# player_guide: The Program Guide (was Check Your Notes).
	[[&"player_guide"], "\"Uh... let me just check the Program Guide...\"", [], [], []],
	[[&"player_guide"], "\"Bear with me, it's all in the Program Guide.\"", [], [], []],
	[[&"player_guide"], "\"Hold on, let me look that up real quick.\"", [], [], []],
	[[&"player_guide"], "\"It's on the tip of my tongue...\"", [], [], []],
	[[&"player_guide"], "\"Where did I put that brochure...\"", [], [], []],

	[[&"player_comp"], "\"Good news, everyone! A year of WALKAWAY, on the house!\"", [], [], []],
	[[&"player_comp"], "\"Today only, everyone gets a free year of protection!\"", [], [], []],
	[[&"player_comp"], "\"Consider it a gift from the dealership.\"", [], [], []],
	[[&"player_comp"], "\"It's on us. No, really. Free.\"", [], [], []],

	[[&"player_justthething"], "\"Oh, I have just the product for you!\"", [], [], []],
	[[&"player_justthething"], "\"Wait, wait. I know exactly what you need.\"", [], [], []],
	[[&"player_justthething"], "\"You know what? I've got the perfect thing.\"", [], [], []],
	[[&"player_justthething"], "\"Say no more. I've got just the thing.\"", [], [], []],

	[[&"player_rightword"], "\"I know I have a word track for this...\"", [], [], []],
	[[&"player_rightword"], "\"Let me put it this way...\"", [], [], []],
	[[&"player_rightword"], "\"Okay, here's how I explain it to my own mother.\"", [], [], []],
	[[&"player_rightword"], "\"You know what they say about peace of mind...\"", [], [], []],

	[[&"player_smile"], "\"Hi! So glad you're here!\"", [], [], []],
	[[&"player_smile"], "\"Welcome, welcome! Make yourself comfortable.\"", [], [], []],
	[[&"player_smile"], "\"Big day! Congratulations on the new ride!\"", [], [], []],
	[[&"player_smile"], "\"You're going to love this car. I just know it.\"", [], [], []],
	[[&"player_smile"], "\"Isn't this exciting?\"", [], [], []],
	[[&"player_smile"], "\"So lovely to see you. Truly.\"", [&"karen"], [], []],

	[[&"player_jazz"], "\"Let me just put a little music on.\"", [], [], []],
	[[&"player_jazz"], "\"Anybody mind a little smooth jazz?\"", [], [], []],
	[[&"player_jazz"], "\"Ah, saxophone. Instantly calming, isn't it?\"", [], [], []],
	[[&"player_jazz"], "\"Everybody just breathe. Enjoy the tunes.\"", [], [], []],

	# player_close: the trial close, said by offer() itself as you ask.
	[[&"player_close"], "\"So, shall I add it in?\"", [], [], []],
	[[&"player_close"], "\"Can you see how that'd be worth it?\"", [], [], []],
	[[&"player_close"], "\"Should we put you down for it?\"", [], [], []],
	[[&"player_close"], "\"Sound good? Let's get you protected.\"", [], [], []],
	[[&"player_close"], "\"Sign here, here, and initial here.\"", [], [], []],

	# --------------------------------------------------------- THEIR SIDE
	# interested: said instead of an objection when the product you put down
	# already clears their Line - see Shift._object().
	[[&"interested"], "\"Oh, that actually sounds good.\"", [], [], []],
	[[&"interested"], "\"Okay, I like the sound of that.\"", [], [], []],
	[[&"interested"], "\"Huh. That's right up my alley.\"", [], [], []],
	[[&"interested"], "\"Finally, something sensible.\"", [&"karen"], [], []],

	# reply_*: their answer to one of the method's techniques, where nothing
	# was written for the objection they have open (or none is).
	[[&"reply_empathize"], "\"Thanks. I appreciate that.\"", [], [], []],
	[[&"reply_empathize"], "\"Okay. I'm listening.\"", [], [], []],
	[[&"reply_empathize"], "\"That's fair, I guess.\"", [], [], []],
	[[&"reply_clarify"], "\"Honestly? I'm not sure.\"", [], [], []],
	[[&"reply_clarify"], "\"It's just a lot to think about.\"", [], [], []],
	[[&"reply_clarify"], "\"Do I have to answer all these questions?\"", [], [], []],
	[[&"reply_clarify"], "\"Why do you need to know that?\"", [&"karen"], [], []],
	[[&"reply_relate"], "\"Ha. Fair enough.\"", [], [], []],
	[[&"reply_relate"], "\"Okay, that makes it easier to picture.\"", [], [], []],
	[[&"reply_relate"], "\"I do drink a lot of coffee.\"", [], [], []],
	[[&"reply_value"], "\"Huh. When you put it that way...\"", [], [], []],
	[[&"reply_value"], "\"Okay, that's worth something.\"", [], [], []],
	[[&"reply_budget"], "\"Okay, that's more like it.\"", [], [], []],
	[[&"reply_listen"], "\"Honestly, I just want something reliable.\"", [], [], []],
	[[&"reply_listen"], "\"I just don't want any surprises.\"", [], [], []],
	[[&"reply_listen"], "\"We've got a baby on the way, so...\"", [&"family"], [], []],
	[[&"reply_listen"], "\"I've read every review of this car. Twice.\"", [&"tech"], [], []],
	[[&"reply_listen"], "\"I just want this done today.\"", [&"kicker"], [], []],
]

## Each of the method's techniques: [the tag your line goes in, the tag their
## answer goes in]. &"" for no answer - the guide is you looking something up,
## and the close is answered by the yes (accepted) or the no that follows it.
const TECHNIQUES := {
	"empathize": [&"player_empathize", &"reply_empathize"],
	"clarify": [&"player_clarify", &"reply_clarify"],
	"relate": [&"player_relate", &"reply_relate"],
	"value": [&"player_value", &"reply_value"],
	"budget": [&"player_budget", &"reply_budget"],
	"listen": [&"player_listen", &"reply_listen"],
	"guide": [&"player_guide", &""],
	"close": [&"player_close", &""],
}

# ------------------------------------------------------------- OBJECTIONS
# One entry per objection, laid out the way the deck lays them out.
#
# "raise" is how a customer brings it up: [the tag a product asks for in its
# objection_tags, rows], each row [text, archetype_ids, product_ids] with the
# last two optional - an archetype row is the deck's "getting ahead of
# objections": who tends to raise it. Saying any of them opens this objection.
# No "raise" means it is only ever flushed out of another.
#
# Each technique is [your line, their answer], either of which may be "". An
# answer can instead be a list of [text, objection] pairs, where answering
# flushes out the real objection behind this one - "No thanks" turning out to
# be the price.
const OBJECTIONS := [
	# ---- WALKAWAY: the deck's own, condensed.
	{"id": &"walkaway_too_expensive",
		"raise": [&"objection_walkaway", [
			["\"It's too expensive.\""],
			["\"That's a lot to add to my payment.\""],
			["\"Whoa. How much a month is that?\"", [&"hawk"]],
			["\"I'm not paying extra for that.\"", [&"karen"]],
		]],
		"clarify": ["\"So you see the benefit, it's just more than you want to spend?\"", "\"Well, yeah.\""],
		"empathize": ["\"I can appreciate that. We have options for every budget.\"", "\"Okay. Like what?\""],
		"budget": ["\"Standard Plus 4 is great protection, under $7 a payment.\"", "\"Under seven bucks? Huh.\""],
		"relate": ["\"Would 4 months get you back on your feet, or a full year?\"", "\"A full year would be nice.\""],
		"value": ["\"A full year of payments covered, for a few dollars more.\"", "\"When you put it like that...\""],
		"listen": ["\"What were you hoping to keep the payment at?\"", "\"Somewhere under five hundred.\""],
		"guide": ["\"It says here Plus 4 covers 4 payments instead of 12.\""],
		"close": ["\"Four months covered, or the whole year?\""],
	},
	{"id": &"walkaway_no_thanks",
		"raise": [&"objection_walkaway", [
			["\"No thanks.\""],
			["\"I think I'll pass.\""],
			["\"No thanks. Can we wrap this up?\"", [&"kicker"]],
			["\"No. Absolutely not.\"", [&"karen"]],
		]],
		"clarify": ["\"Is it the payment, or you don't see yourself using it?\"", [
			["\"Honestly? It's the payment.\"", &"walkaway_too_expensive"],
			["\"I just don't see myself needing it.\"", &"walkaway_dont_need"],
		]],
		"listen": ["\"No pressure. What's making you hesitate?\"", [
			["\"It's the money, mostly.\"", &"walkaway_too_expensive"],
			["\"I don't think I'd ever use it.\"", &"walkaway_dont_need"],
		]],
		"empathize": ["\"No problem at all. Most people say that at first.\"", "\"Yeah, I'm just not sure.\""],
		"guide": ["\"Can I show you one page of the Program Guide? It's quick.\""],
	},
	{"id": &"walkaway_dont_need",
		"raise": [&"objection_walkaway", [
			["\"I don't think I need it.\""],
			["\"I don't see myself using it.\""],
			["\"Ah, I don't think I'll ever need that.\"", [&"easygoing"]],
		]],
		"clarify": ["\"Because you won't get sick or laid off, or you have a plan?\"", "\"I just don't see it happening.\""],
		"empathize": ["\"Totally understand, and hopefully you never do.\"", "\"Right. Exactly.\""],
		"relate": ["\"It's like a car warranty. Built well, but you never know.\"", "\"Huh. I guess that's fair.\""],
		"value": ["\"That's why most clients like a warranty for themselves.\"", "\"A warranty for me. Okay.\""],
		"listen": ["\"If you lost your job, how would you make the payments?\"", [
			["\"From my savings, I guess.\"", &"walkaway_savings"],
			["\"I'd use my line of credit.\"", &"walkaway_line_of_credit"],
		]],
		"close": ["\"Can you see how that might be of value to you, too?\""],
	},
	{"id": &"walkaway_savings",
		"empathize": ["\"It's great you're in a position to do that.\"", "\"I've worked hard for it.\""],
		"listen": ["\"What are those savings for, ideally?\"", "\"A rainy day. Maybe a trip.\""],
		"relate": ["\"Savings are for the fun stuff, not the car payment.\"", "\"...Fair point.\""],
		"value": ["\"Most people like you protect their savings for something they want.\"", "\"Like a trip, or the kids' school.\""],
		"close": ["\"Wouldn't you rather keep those savings for yourself?\""],
	},
	{"id": &"walkaway_line_of_credit",
		"empathize": ["\"Good to have that option.\"", "\"It's there for emergencies.\""],
		"listen": ["\"What else is that line of credit there for?\"", "\"Emergencies, mostly.\""],
		"relate": ["\"If something happened, you'd need that credit for other bills.\"", "\"Hm. I hadn't thought of that.\""],
		"value": ["\"For a few dollars, your biggest bill is taken care of.\"", "\"That would take some stress off.\""],
		"close": ["\"Can you see why most people protect that line of credit?\""],
	},
	{"id": &"walkaway_work_coverage",
		"raise": [&"objection_walkaway", [
			["\"I have great coverage through work.\""],
			["\"My work benefits already cover all that.\"", [&"tech"]],
		]],
		"empathize": ["\"That's great. Employers who care make a big difference.\"", "\"Yeah, they're pretty good to us.\""],
		"listen": ["\"What does your plan at work actually pay?\"", "\"Most of my salary, I think?\""],
		"clarify": ["\"To be blunt, the best plans I know pay only 67% on disability.\"", "\"Wait, only 67 percent?\""],
		"relate": ["\"I don't know about you, but I spend more than two thirds of my pay!\"", "\"Ha. Don't we all.\""],
		"value": ["\"WALKAWAY tops that up, on top of any other benefit you get.\"", "\"On top of it? Okay.\""],
		"close": ["\"Can you see how $15 for $25,000 of benefits could come in handy?\""],
	},
	{"id": &"walkaway_lots_of_insurance",
		"raise": [&"objection_walkaway", [
			["\"I already have lots of insurance.\""],
			["\"We already have life insurance for the kids.\"", [&"family"]],
		]],
		"empathize": ["\"That's great news! It's always great to be protected.\"", "\"I like to be careful.\""],
		"listen": ["\"Who is that policy meant to look after?\"", "\"My family, of course.\""],
		"clarify": ["\"Would that policy end up paying off the car?\"", "\"I mean... I guess it would.\""],
		"value": ["\"This keeps your life insurance from paying off the car.\"", "\"Huh. I never thought of that.\""],
		"relate": ["\"That way, your loved ones keep more of that money.\"", "\"That does matter to me.\""],
		"close": ["\"Isn't a few dollars a solid way to protect that inheritance?\""],
	},
	{"id": &"walkaway_wont_qualify",
		"raise": [&"objection_walkaway", [
			["\"I wouldn't qualify for that.\""],
			["\"I probably wouldn't even qualify.\"", [&"laydown"]],
		]],
		"empathize": ["\"I hear that a lot. You'd be surprised.\"", "\"Would I, though?\""],
		"listen": ["\"What makes you think you wouldn't?\"", "\"My health isn't the best.\""],
		"clarify": ["\"Everyone under 80 qualifies. No pre-existing condition clauses.\"", "\"Really? None at all?\""],
		"value": ["\"No good health statements, and no medical checks.\"", "\"Well, that's easy enough.\""],
		"guide": ["\"It's right here in the Program Guide: no medical checks.\""],
		"close": ["\"So nothing's standing in your way. Shall we add it?\""],
	},
	{"id": &"walkaway_buy_outright",
		"raise": [&"objection_walkaway", [
			["\"I'd just buy the car outright.\""],
			["\"If it came to that, I'd just pay it off.\""],
			["\"I'd just pay the thing off in cash.\"", [&"hawk"]],
		]],
		"empathize": ["\"That's a great position to be in. Fantastic flexibility.\"", "\"I've been saving a while.\""],
		"listen": ["\"What would that do to your savings?\"", "\"Put a dent in them, sure.\""],
		"clarify": ["\"Would you rather spend those savings, or keep them?\"", "\"Keep them, obviously.\""],
		"value": ["\"Many in your spot keep their savings intact for hard times.\"", "\"I do like having a cushion.\""],
		"close": ["\"Would that kind of flexibility be of value to you too?\""],
	},

	# ---- WALKAWAY GAP: the same method, paraphrased for the gap between the
	# loan and the payout.
	{"id": &"walkaway_gap_too_expensive",
		"raise": [&"objection_walkaway_gap", [
			["\"It's too expensive.\""],
			["\"That's a lot just for a 'what if.'\""],
			["\"How much is THAT going to run me?\"", [&"hawk"]],
		]],
		"clarify": ["\"So you like the idea, it's just the price?\"", "\"Pretty much.\""],
		"empathize": ["\"Totally fair. Nobody wants a bigger payment.\"", "\"No kidding.\""],
		"relate": ["\"It's less than a tank of gas a month.\"", "\"Huh. Really?\""],
		"value": ["\"Total the car, and you won't be paying for one you lost.\"", "\"That would be awful.\""],
		"budget": ["\"Spread over the loan, it's a few dollars a payment.\"", "\"Okay, that's not bad.\""],
		"listen": ["\"Where were you hoping to keep the payment?\"", "\"As low as it'll go.\""],
		"close": ["\"Want that gap covered for a few dollars?\""],
	},
	{"id": &"walkaway_gap_insured",
		"raise": [&"objection_walkaway_gap", [
			["\"My car insurance covers that.\""],
			["\"Doesn't my insurance already cover that?\"", [&"tech"]],
		]],
		"empathize": ["\"Good, you should have that.\"", "\"Exactly.\""],
		"clarify": ["\"Insurance pays what the car's worth, not what you owe.\"", "\"Wait, those aren't the same?\""],
		"listen": ["\"And what would your insurance pay out, do you think?\"", "\"What it's worth, I guess.\""],
		"relate": ["\"New cars lose value fast. Your loan doesn't.\"", "\"Huh. Good point.\""],
		"value": ["\"This covers the difference, so you don't pay off a car you lost.\"", "\"Okay, that makes sense.\""],
		"close": ["\"Shall we close that gap?\""],
	},
	{"id": &"walkaway_gap_dont_need",
		"raise": [&"objection_walkaway_gap", [
			["\"I'm not planning on wrecking it.\""],
			["\"I'm a careful driver.\""],
		]],
		"clarify": ["\"If it's ever totaled, how would you cover the rest of the loan?\"", "\"I... honestly don't know.\""],
		"listen": ["\"What would you do if it was stolen tomorrow?\"", [
			["\"Call my insurance, I guess?\"", &"walkaway_gap_insured"],
		]],
		"empathize": ["\"I'm sure you are. Hopefully you never need it.\"", "\"I hope not.\""],
		"relate": ["\"Nobody plans it. That's why they call it an accident.\"", "\"Ha. Fair enough.\""],
		"value": ["\"Fire, theft or accident, the gap is covered.\"", "\"Even theft? Huh.\""],
		"close": ["\"Can you see how that might be worth a few dollars?\""],
	},
	{"id": &"walkaway_gap_no_thanks",
		"raise": [&"objection_walkaway_gap", [
			["\"No thanks.\""],
			["\"No. Absolutely not.\"", [&"karen"]],
		]],
		"clarify": ["\"Is it the price, or you don't see yourself needing it?\"", [
			["\"It's the price.\"", &"walkaway_gap_too_expensive"],
			["\"I just don't think I'll need it.\"", &"walkaway_gap_dont_need"],
		]],
		"listen": ["\"No pressure. What's holding you back?\"", [
			["\"It's the money, really.\"", &"walkaway_gap_too_expensive"],
			["\"My insurance covers that, right?\"", &"walkaway_gap_insured"],
		]],
	},

	# ---- Everything else: generic, plus a joke per product. No value lines
	# here on purpose - Back to Value falls back to the product's own pitch.
	{"id": &"too_expensive",
		"raise": [&"objection", [
			["\"It's too expensive.\""],
			["\"What's that going to cost me?\""],
			["\"Fine. What's the other guy charging for it?\"", [&"hawk"]],
			["\"I'm not paying for that.\"", [&"karen"]],
		]],
		"clarify": ["\"So you like it, it's just the price?\"", "\"Pretty much.\""],
		"empathize": ["\"Totally fair. Nobody wants a bigger payment.\"", "\"No kidding.\""],
		"budget": ["\"Let me see what I can do on the price.\"", "\"Now we're talking.\""],
		"relate": ["\"That's about three coffees a week.\"", "\"I do drink a lot of coffee.\""],
		"close": ["\"If I can make the number work, are we good?\""],
	},
	{"id": &"dont_need",
		"raise": [&"objection", [
			["\"I don't think I need that.\""],
			["\"Do I look like I need all that?\""],
			["\"My cousin's a mechanic. Sort of.\"", [], [&"vsc"]],
			["\"Who would steal THIS car?\"", [], [&"theft"]],
			["\"I'll just wash it more. Probably.\"", [], [&"appearance"]],
			["\"I like waiting rooms. Free coffee.\"", [], [&"concierge"]],
			["\"The heaviest thing I tow is groceries.\"", [], [&"perf"]],
			["\"I'm never getting laid off. I'm the boss's nephew.\"", [], [&"ppp"]],
			["\"I've never missed a payment in my life.\"", [], [&"flex"]],
			["\"I'm driving this until the wheels fall off.\"", [], [&"tvp"]],
			["\"I'm a really good driver, though.\"", [], [&"gap"]],
		]],
		"clarify": ["\"What makes you feel you won't need it?\"", "\"It's just never come up.\""],
		"empathize": ["\"Fair. A lot of people feel that way at first.\"", "\"Glad it's not just me.\""],
		"relate": ["\"Nobody needs an umbrella until it rains.\"", "\"Ha. Okay, okay.\""],
		"close": ["\"Can you see how it might be worth having?\""],
	},
	{"id": &"no_thanks",
		"raise": [&"objection", [
			["\"No thanks.\""],
			["\"I'll pass.\""],
			["\"No thanks. Are we almost done?\"", [&"kicker"]],
		]],
		"clarify": ["\"Is it the price, or the product?\"", [
			["\"It's the price.\"", &"too_expensive"],
			["\"I don't think I need it.\"", &"dont_need"],
		]],
		"listen": ["\"No pressure. What's holding you back?\"", [
			["\"It's the money, mostly.\"", &"too_expensive"],
			["\"I just don't need it.\"", &"dont_need"],
		]],
		"empathize": ["\"No problem at all. Can I ask why?\"", "\"Just not sure it's worth it.\""],
	},
]

func _init() -> void:
	DirAccess.make_dir_recursive_absolute(DIR)

	var built: Array[DialogueLine] = []
	for row in LINES:
		built.append(_line(row[0], row[1], row[2], row[3], row[4]))
	for o in OBJECTIONS:
		built.append_array(_objection_lines(o))

	var pool := DialoguePool.new()
	pool.design_rule = DESIGN_RULE
	pool.known_tags.assign(KNOWN_TAGS)
	pool.known_objections.assign(KNOWN_OBJECTIONS)
	pool.lines = built
	var err := ResourceSaver.save(pool, "%s/dialogue_pool.tres" % DIR)
	if err != OK:
		push_error("failed to save dialogue_pool.tres: %d" % err)
		quit(1)
		return

	print("built %d lines across %d tags and %d objections"
		% [built.size(), KNOWN_TAGS.size(), KNOWN_OBJECTIONS.size()])
	quit(0)


func _line(tags: Array, text: String, archetypes: Array = [], products: Array = [],
		bands: Array = [], objections: Array = [],
		becomes: StringName = &"") -> DialogueLine:
	var l := DialogueLine.new()
	l.tags.assign(tags)
	l.text = text
	l.archetype_ids.assign(archetypes)
	l.product_ids.assign(products)
	l.appeal_bands.assign(bands)
	l.objection_ids.assign(objections)
	l.becomes = becomes
	return l


## One OBJECTIONS entry, as lines: its raises, each opening it, then each
## technique's line for it and their answer to that.
func _objection_lines(o: Dictionary) -> Array[DialogueLine]:
	var id: StringName = o["id"]
	var out: Array[DialogueLine] = []
	if o.has("raise"):
		var tag: StringName = o["raise"][0]
		for r in o["raise"][1]:
			out.append(_line([tag], r[0], r[1] if r.size() > 1 else [],
				r[2] if r.size() > 2 else [], [], [], id))
	for technique in TECHNIQUES:
		if not o.has(technique):
			continue
		var said: Array = o[technique]
		var yours: StringName = TECHNIQUES[technique][0]
		var theirs: StringName = TECHNIQUES[technique][1]
		if said[0] != "":
			out.append(_line([yours], said[0], [], [], [], [id]))
		if said.size() < 2 or theirs == &"":
			continue
		if said[1] is String:
			if said[1] != "":
				out.append(_line([theirs], said[1], [], [], [], [id]))
			continue
		for flush in said[1]:
			out.append(_line([theirs], flush[0], [], [], [], [id], flush[1]))
	return out
