extends SceneTree
## Regenerates res://data/dialogue/dialogue_pool.tres from the rows below.
##
##     godot --headless --path game --script res://tools/build_dialogue.gd
##
## UNLIKE seed_interests.gd and its siblings, this is a BUILD STEP, not a
## bootstrap - it is re-run whenever a line changes, and the .tres it writes
## is an artifact, not the source of truth. Edit dialogue HERE. Anything typed
## into the Inspector is gone on the next run.
##
## The distinction is the same one build_*_scene.gd already draws. Interests,
## cards and archetypes are STRUCTURED data with cross-references a designer
## genuinely tunes in the Inspector - dragging an Interest into top_interests.
## Dialogue is PROSE: nothing to drag, the payload is a sentence, and the file
## will run to hundreds of them. A 200-element array of collapsed sub-resources
## is a bad text editor and a worse diff.

const DIR := "res://data/dialogue"

const KNOWN_TAGS := [&"appeal", &"patience", &"concession", &"pressure",
	&"padding", &"demand_thinking", &"demand_restless", &"demand_manager",
	&"demand_show_me", &"demand_better_quote", &"relief", &"ignored",
	&"accepted", &"impatient"]

const DESIGN_RULE := "One library, divided by TAG, not by file. A line's tags say which pool it belongs to and are the only required match; archetype_ids, product_ids and appeal_bands are optional narrowings, and an empty one means any. Narrowing is additive and exclusive: a line naming karen is unavailable to everybody else, never merely less likely. Every tag must keep at least one line with NO narrowings at all - that is the fallback that stops a pool going silent, and the suite enforces it. Specific lines are WEIGHTED over generic ones, never substituted for them: one karen line must not make ten generic ones unreachable, or every karen says the same sentence for the rest of the run. GENERATED by tools/build_dialogue.gd - edit the rows there, not this file."

# tags, text, archetype_ids, product_ids, appeal_bands
const LINES := [
	[[&"appeal"], "\"Okay. Keep talking.\"", [], [], []],
	[[&"appeal"], "\"Huh. I had not thought about it that way.\"", [], [], []],
	[[&"appeal"], "\"That is not nothing, I will give you that.\"", [], [], []],
	[[&"appeal"], "\"Alright. I am listening.\"", [], [], []],
	[[&"appeal"], "\"My brother-in-law said the same about these.\"", [], [], []],

	[[&"appeal"], "\"You are not really selling me here.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"It still feels like a lot for what it is.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"You are very close to a yes, you know.\"", [], [], [&"ALMOST"]],
	[[&"appeal"], "\"Say that last part one more time.\"", [], [], [&"ALMOST"]],

	[[&"appeal"], "\"And is that in writing, or just you saying it?\"", [&"karen"], [], []],
	[[&"appeal"], "\"Fine. What is the other guy charging for that?\"", [&"hawk"], [], []],
	[[&"appeal"], "\"Do you have the actual spec sheet on that?\"", [&"tech"], [], []],
	[[&"appeal"], "\"Sure, sure. How much longer is this going to be?\"", [&"kicker"], [], []],
	[[&"appeal"], "\"Let me run that past her before I say anything.\"", [&"family"], [], []],

	[[&"appeal"], "\"So if I total it, that is the part that covers me?\"", [], [&"gap"], []],
	[[&"appeal"], "\"And this is on top of the factory warranty?\"", [], [&"vsc"], []],

	[[&"patience"], "\"Ha. The 401 was a parking lot this morning too.\"", [], [], []],
	[[&"patience"], "\"No rush on my end. I took the afternoon.\"", [], [], []],
	[[&"patience"], "\"You are alright, you know that?\"", [], [], []],
	[[&"patience"], "\"My daughter has a game at six, but we are fine.\"", [], [], []],
	[[&"patience"], "\"That is nice. The meter is still running though.\"", [&"kicker"], [], []],

	[[&"concession"], "\"Now you are speaking my language.\"", [], [], []],
	[[&"concession"], "\"See, that is what I was waiting for.\"", [], [], []],
	[[&"concession"], "\"Better. Still not what the place on Dundas quoted.\"", [&"hawk"], [], []],

	[[&"pressure"], "\"Alright, alright. You do not have to lean on me.\"", [], [], []],
	[[&"pressure"], "\"Okay. Fine. Just stop.\"", [], [], []],
	[[&"pressure"], "\"Do not take that tone with me.\"", [&"karen"], [], []],

	[[&"padding"], "\"Sure. Whatever the paperwork says.\"", [], [], []],
	[[&"padding"], "\"I will take your word on the numbers.\"", [], [], []],

	# Migrated verbatim from CustomerAction.dialogue / Demand.dialogue -
	# nothing that was already spoken changes here, it just moves into the
	# tagged system. Each demand-raise tag keeps exactly one line for now;
	# the point of the migration is that adding a second is now a data edit.
	[[&"demand_thinking"], "\"Could we have a moment?\"", [], [], []],
	[[&"demand_restless"], "\"How long is this going to take?\"", [], [], []],
	[[&"demand_manager"], "\"Is there someone else I can speak to?\"", [], [], []],
	[[&"demand_show_me"], "\"What have you got that is actually worth having?\"", [], [], []],
	[[&"demand_better_quote"], "\"I had another dealer at less than that.\"", [], [], []],
	# Demand.dialogue's own text was never actually spoken anywhere before
	# this migration (dead data - _settle_demand() hardcoded "" always), so
	# it is not "the" line for this tag - it becomes a second, free variant.
	[[&"demand_better_quote"], "\"The place on Dundas does this for less.\"", [], [], []],

	# New: demand settlement never spoke at all before this migration
	# (_settle_demand() hardcoded dialogue to "" unconditionally). Generic
	# for now - a specific demand can narrow these later the same way any
	# other tag narrows, by adding archetype/product/band filters.
	[[&"relief"], "\"Alright, that works.\"", [], [], []],
	[[&"relief"], "\"Good. That is all I wanted.\"", [], [], []],
	[[&"relief"], "\"Now we are getting somewhere.\"", [], [], []],
	[[&"ignored"], "\"Fine. Forget it.\"", [], [], []],
	[[&"ignored"], "\"Whatever you say.\"", [], [], []],
	[[&"ignored"], "\"I will remember that.\"", [], [], []],

	# Not asked for by any card, action or demand - Shift says these itself.
	# accepted: the moment an offer clears their Line and they take it. Where a
	# line names a product, it is about the one they just took.
	[[&"accepted"], "\"Alright. Put me down for that one.\"", [], [], []],
	[[&"accepted"], "\"Yeah, okay. I can see that being worth it.\"", [], [], []],
	[[&"accepted"], "\"You know what? Sold.\"", [], [], []],
	[[&"accepted"], "\"Good. That is one less thing to worry about.\"", [], [], []],
	[[&"accepted"], "\"Fine, you got me. I will take it.\"", [], [], []],
	[[&"accepted"], "\"Fine. But I want all of that in writing.\"", [&"karen"], [], []],
	[[&"accepted"], "\"At that number? Alright, I can live with it.\"", [&"hawk"], [], []],
	[[&"accepted"], "\"Nice. I will read the fine print tonight.\"", [&"tech"], [], []],
	[[&"accepted"], "\"She is going to be glad we got that one.\"", [&"family"], [], []],
	[[&"accepted"], "\"Sure, sure. Throw it on. Are we done?\"", [&"kicker"], [], []],
	[[&"accepted"], "\"Sounds good to me!\"", [&"easygoing"], [], []],
	[[&"accepted"], "\"Yep. Whatever you think is best.\"", [&"laydown"], [], []],
	[[&"accepted"], "\"Good. I am not paying off a car I do not have.\"", [], [&"gap"], []],
	[[&"accepted"], "\"No more surprise repair bills. I like that.\"", [], [&"vsc"], []],
	[[&"accepted"], "\"Given my street? Yes, please.\"", [], [&"theft"], []],
	[[&"accepted"], "\"So my trade-in keeps its value. Smart.\"", [], [&"tvp"], []],
	[[&"accepted"], "\"The wheels on my last car were a mess. Deal.\"", [], [&"appearance"], []],
	[[&"accepted"], "\"If I lose my job, the payments are covered? Done.\"", [], [&"ppp"], []],
	[[&"accepted"], "\"Somebody to call at two in the morning? I will take it.\"", [], [&"concierge"], []],
	[[&"accepted"], "\"A little breathing room on the payments. Good.\"", [], [&"flex"], []],
	[[&"accepted"], "\"Towing and a tune-up? Now you are talking.\"", [], [&"perf"], []],

	# impatient: the moment their patience drops to ShiftConfig.impatient_at or
	# under - once per dip, not once per tick spent down there.
	[[&"impatient"], "\"Are we almost done here?\"", [], [], []],
	[[&"impatient"], "\"I really do not have all day.\"", [], [], []],
	[[&"impatient"], "\"Can we speed this up a little?\"", [], [], []],
	[[&"impatient"], "\"I am starting to lose my patience.\"", [], [], []],
	[[&"impatient"], "\"My parking runs out soon, you know.\"", [], [], []],
	[[&"impatient"], "\"I have been sitting here for AGES.\"", [&"karen"], [], []],
	[[&"impatient"], "\"Every minute in this chair is costing me money.\"", [&"hawk"], [], []],
	[[&"impatient"], "\"I could have read the whole manual by now.\"", [&"tech"], [], []],
	[[&"impatient"], "\"The kids are about to lose it back there.\"", [&"family"], [], []],
	[[&"impatient"], "\"Yeah, I think I am just going to go.\"", [&"kicker"], [], []],
	[[&"impatient"], "\"Not to rush you, but I have somewhere to be.\"", [&"easygoing"], [], []],
	[[&"impatient"], "\"Just tell me where to sign, okay?\"", [&"laydown"], [], []],
]

func _init() -> void:
	DirAccess.make_dir_recursive_absolute(DIR)

	var built: Array[DialogueLine] = []
	for row in LINES:
		var l := DialogueLine.new()
		l.tags.assign(row[0])
		l.text = row[1]
		l.archetype_ids.assign(row[2])
		l.product_ids.assign(row[3])
		l.appeal_bands.assign(row[4])
		built.append(l)

	var pool := DialoguePool.new()
	pool.design_rule = DESIGN_RULE
	pool.known_tags.assign(KNOWN_TAGS)
	pool.lines = built
	var err := ResourceSaver.save(pool, "%s/dialogue_pool.tres" % DIR)
	if err != OK:
		push_error("failed to save dialogue_pool.tres: %d" % err)
		quit(1)
		return

	print("built %d lines across %d tags" % [built.size(), KNOWN_TAGS.size()])
	quit(0)
