extends SceneTree
## Regenerates res://data/dialogue/dialogue_pool.tres from the rows below.
##
##     godot --headless --path game --script res://tools/build_dialogue.gd
##
## UNLIKE seed_interests.gd and its siblings, this is a BUILD STEP, not a
## bootstrap - it is re-run whenever a line changes, and the .tres it writes
## is an artifact, not the source of truth. Edit dialogue HERE. Anything typed
## into the Inspector is gone on the next run.
##
## The distinction is the same one build_*_scene.gd already draws. Interests,
## cards and archetypes are STRUCTURED data with cross-references a designer
## genuinely tunes in the Inspector - dragging an Interest into top_interests.
## Dialogue is PROSE: nothing to drag, the payload is a sentence, and the file
## will run to hundreds of them. A 200-element array of collapsed sub-resources
## is a bad text editor and a worse diff.

const DIR := "res://data/dialogue"

const KNOWN_TAGS := [&"appeal", &"patience", &"concession", &"pressure",
	&"padding", &"demand_thinking", &"demand_restless", &"demand_manager",
	&"demand_show_me", &"demand_better_quote", &"relief", &"ignored",
	&"accepted", &"impatient",
	# Objections - see ProductCardDef.objection_tags and Shift._object(). The
	# warm word instead, when a product already clears their Line.
	&"objection", &"objection_walkaway", &"objection_walkaway_gap", &"interested",
	# Their answers to the method's techniques - the reskinned appeal cards.
	&"reply_empathize", &"reply_clarify", &"reply_relate", &"reply_value",
	&"reply_budget", &"reply_listen",
	# Yours - see CardDef.player_dialogue_tags. player_close is the trial
	# close offer() says itself.
	&"player_pitch", &"player_smalltalk", &"player_empathize",
	&"player_budget", &"player_value", &"player_fearmonger",
	&"player_relate", &"player_clarify", &"player_pad", &"player_listen",
	&"player_guide", &"player_comp", &"player_justthething",
	&"player_rightword", &"player_smile", &"player_jazz", &"player_close"]

## Every objection a customer can be working through. The walkaway_ ones are
## the deck's ("Handling Objections", WALKAWAY Webinar Series 4), condensed;
## the bare ones are everybody else's. savings and line_of_credit are never
## raised outright - asking "how would you make the payments?" flushes them out.
const KNOWN_OBJECTIONS := [
	&"walkaway_too_expensive", &"walkaway_no_thanks", &"walkaway_dont_need",
	&"walkaway_savings", &"walkaway_line_of_credit", &"walkaway_work_coverage",
	&"walkaway_lots_of_insurance", &"walkaway_wont_qualify",
	&"walkaway_buy_outright",
	&"walkaway_gap_too_expensive", &"walkaway_gap_insured",
	&"walkaway_gap_dont_need", &"walkaway_gap_no_thanks",
	&"too_expensive", &"dont_need", &"no_thanks"]

const DESIGN_RULE := "One library, divided by TAG, not by file. A line's tags say which pool it belongs to and are the only required match; archetype_ids, product_ids, appeal_bands and objection_ids are optional narrowings, and an empty one means any. Narrowing is additive and exclusive: a line naming karen is unavailable to everybody else, never merely less likely. Every tag must keep at least one line with NO narrowings at all - that is the fallback that stops a pool going silent, and the suite enforces it. Specific lines are WEIGHTED over generic ones, never substituted for them: one karen line must not make ten generic ones unreachable, or every karen says the same sentence for the rest of the run. The one exception is an open objection: where lines answer it, only they are drawn, because the word track written for it IS the answer. A line's `becomes` opens or moves the customer's objection when it is said. The player_* tags are YOUR lines, asked for by a card's player_dialogue_tags; on those, an archetype narrowing means who you are talking to. GENERATED by tools/build_dialogue.gd - edit the rows there, not this file."

# tags, text, archetype_ids, product_ids, appeal_bands
const LINES := [
	[[&"appeal"], "\"Okay. Keep talking.\"", [], [], []],
	[[&"appeal"], "\"Huh. I had not thought about it that way.\"", [], [], []],
	[[&"appeal"], "\"That is not nothing, I will give you that.\"", [], [], []],
	[[&"appeal"], "\"Alright. I am listening.\"", [], [], []],
	[[&"appeal"], "\"Oh, I've heard of that.\"", [], [], []],

	[[&"appeal"], "\"You are not really selling me here.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"It still feels like a lot for what it is.\"", [], [], [&"COLD"]],
	[[&"appeal"], "\"Okay, I can see how that would be helpful.\"", [], [], [&"ALMOST"]],
	[[&"appeal"], "\"Oh, that's pretty good.\"", [], [], [&"ALMOST"]],

	[[&"appeal"], "\"And is that in writing, or just you saying it?\"", [&"karen"], [], []],
	[[&"appeal"], "\"Fine. What is the other guy charging for that?\"", [&"hawk"], [], []],
	[[&"appeal"], "\"Do you have the actual spec sheet on that?\"", [&"tech"], [], []],
	[[&"appeal"], "\"Sure, sure. How much longer is this going to be?\"", [&"kicker"], [], []],
	[[&"appeal"], "\"Let me run that past my partner before I say anything.\"", [&"family"], [], []],

	[[&"appeal"], "\"So if I total it, that is the part that covers me?\"", [], [&"gap"], []],
	[[&"appeal"], "\"And this is on top of the factory warranty?\"", [], [&"vsc"], []],


	[[&"patience"], "\"Ha. Yeah.\"", [], [], []],
	[[&"patience"], "\"Oh, totally.\"", [], [], []],
	[[&"patience"], "\"Mm, right?\"", [], [], []],
	[[&"patience"], "\"That is nice, but I really do need to go soon.\"", [&"kicker"], [], []],

	[[&"concession"], "\"Now you are speaking my language.\"", [], [], []],
	[[&"concession"], "\"See, that is what I was waiting for.\"", [], [], []],
	[[&"concession"], "\"Better, but it's still not what the place next door quoted.\"", [&"hawk"], [], []],

	[[&"pressure"], "\"Alright, alright. You do not have to lean on me.\"", [], [], []],
	[[&"pressure"], "\"Okay. Fine. Just stop.\"", [], [], []],
	[[&"pressure"], "\"Do not take that tone with me.\"", [&"karen"], [], []],

	[[&"padding"], "\"Sure. That sounds reasonable.\"", [], [], []],
	[[&"padding"], "\"I will take your word on the numbers.\"", [], [], []],

	# Migrated verbatim from CustomerAction.dialogue / Demand.dialogue -
	# nothing that was already spoken changes here, it just moves into the
	# tagged system. Each demand-raise tag keeps exactly one line for now;
	# the point of the migration is that adding a second is now a data edit.
	[[&"demand_thinking"], "\"Could we have a moment?\"", [], [], []],
	[[&"demand_restless"], "\"How long is this going to take?\"", [], [], []],
	[[&"demand_manager"], "\"Is there someone else I can speak to?\"", [], [], []],
	[[&"demand_show_me"], "\"What have you got that is actually worth having?\"", [], [], []],
	[[&"demand_better_quote"], "\"I had another dealer at less than that.\"", [], [], []],
	# Demand.dialogue's own text was never actually spoken anywhere before
	# this migration (dead data - _settle_demand() hardcoded "" always), so
	# it is not "the" line for this tag - it becomes a second, free variant.
	[[&"demand_better_quote"], "\"The place down the street does this for less.\"", [], [], []],

	# New: demand settlement never spoke at all before this migration
	# (_settle_demand() hardcoded dialogue to "" unconditionally). Generic
	# for now - a specific demand can narrow these later the same way any
	# other tag narrows, by adding archetype/product/band filters.
	[[&"relief"], "\"Alright, that works.\"", [], [], []],
	[[&"relief"], "\"Good. That is all I wanted.\"", [], [], []],
	[[&"relief"], "\"Now we are getting somewhere.\"", [], [], []],
	[[&"ignored"], "\"Fine. Forget it.\"", [], [], []],
	[[&"ignored"], "\"Whatever you say.\"", [], [], []],
	[[&"ignored"], "\"That's not nice.\"", [], [], []],

	# Not asked for by any card, action or demand - Shift says these itself.
	# accepted: the moment an offer clears their Line and they take it. Where a
	# line names a product, it is about the one they just took.
	[[&"accepted"], "\"Alright. Put me down for that one.\"", [], [], []],
	[[&"accepted"], "\"Yeah, okay. I can see that being worth it.\"", [], [], []],
	[[&"accepted"], "\"You know what? Sold.\"", [], [], []],
	[[&"accepted"], "\"Good. That is one less thing to worry about.\"", [], [], []],
	[[&"accepted"], "\"Fine, you got me. I will take it.\"", [], [], []],
	[[&"accepted"], "\"Fine. But I want all of that in writing.\"", [&"karen"], [], []],
	[[&"accepted"], "\"At that number? Alright, I can live with it.\"", [&"hawk"], [], []],
	[[&"accepted"], "\"Nice. I will read the fine print tonight.\"", [&"tech"], [], []],
	[[&"accepted"], "\"My partner is going to be glad we got that one.\"", [&"family"], [], []],
	[[&"accepted"], "\"Sure, sure. Throw it on. Are we done?\"", [&"kicker"], [], []],
	[[&"accepted"], "\"Sounds good to me!\"", [&"easygoing"], [], []],
	[[&"accepted"], "\"Yep. Whatever you think is best.\"", [&"laydown"], [], []],
	[[&"accepted"], "\"Good. I am not paying off a car I do not have.\"", [], [&"gap"], []],
	[[&"accepted"], "\"No more surprise repair bills. I like that.\"", [], [&"vsc"], []],
	[[&"accepted"], "\"Given my street? Yes, please.\"", [], [&"theft"], []],
	[[&"accepted"], "\"So my trade-in keeps its value. Smart.\"", [], [&"tvp"], []],
	[[&"accepted"], "\"The wheels on my last car were a mess. Deal.\"", [], [&"appearance"], []],
	[[&"accepted"], "\"If I lose my job, the payments are covered? Done.\"", [], [&"ppp"], []],
	[[&"accepted"], "\"Somebody to call at two in the morning? I will take it.\"", [], [&"concierge"], []],
	[[&"accepted"], "\"A little breathing room on the payments. Good.\"", [], [&"flex"], []],
	[[&"accepted"], "\"Towing and a tune-up? Now you are talking.\"", [], [&"perf"], []],
	[[&"accepted"], "\"I feel so much more confident about this purchase.\"", [], [&"wap"], []],
	[[&"accepted"], "\"Now I'm confident I'll be covered if it's a total loss.\"", [], [&"tlp"], []],

	# impatient: the moment their patience drops to ShiftConfig.impatient_at or
	# under - once per dip, not once per tick spent down there.
	[[&"impatient"], "\"Are we almost done here?\"", [], [], []],
	[[&"impatient"], "\"I really do not have all day.\"", [], [], []],
	[[&"impatient"], "\"Can we speed this up a little?\"", [], [], []],
	[[&"impatient"], "\"I am starting to lose my patience.\"", [], [], []],
	[[&"impatient"], "\"My parking runs out soon, you know.\"", [], [], []],
	[[&"impatient"], "\"I have been sitting here for AGES.\"", [&"karen"], [], []],
	[[&"impatient"], "\"Every minute in this chair is costing me money.\"", [&"hawk"], [], []],
	[[&"impatient"], "\"I could have read the whole manual by now.\"", [&"tech"], [], []],
	[[&"impatient"], "\"The kids are about to lose it back there.\"", [&"family"], [], []],
	[[&"impatient"], "\"Yeah, I think I am just going to go.\"", [&"kicker"], [], []],
	[[&"impatient"], "\"Not to rush you, but I have somewhere to be.\"", [&"easygoing"], [], []],
	[[&"impatient"], "\"Just tell me where to sign, okay?\"", [&"laydown"], [], []],

	# ------------------------------------------------------------- YOURS
	# What you say as you play a card - see CardDef.player_dialogue_tags. An
	# archetype narrowing here is who you are talking to; a product one is the
	# product on the table (for a product card, the one going down). The
	# method's techniques - empathize, clarify, relate, value, budget, listen -
	# are the reskinned appeal cards. What each says to an OPEN objection is in
	# OBJECTIONS below; these rows are what they say to anything else.
	#
	# Several lines per tag on purpose: a speaker skips what they said lately
	# (DialoguePool.pick_line's `avoid`), so playing a card three times says
	# three different things - as long as there are three things to say.

	# player_pitch: putting a product in front of them.
	[[&"player_pitch"], "\"Now, have you heard about this one?\"", [], [], []],
	[[&"player_pitch"], "\"Can I show you one more thing? It's quick.\"", [], [], []],
	[[&"player_pitch"], "\"This one is really popular this month.\"", [], [], []],
	[[&"player_pitch"], "\"I'd be doing you a disservice if I skipped this one.\"", [], [], []],
	[[&"player_pitch"], "\"Okay, hear me out on this one.\"", [], [], []],
	[[&"player_pitch"], "\"Most people wish they'd bought this one sooner.\"", [], [], []],
	[[&"player_pitch"], "\"I know, I know. Just hear me out.\"", [], [], [&"COLD"]],
	[[&"player_pitch"], "\"Oh, this one is right up your alley.\"", [], [], [&"ALMOST"]],
	[[&"player_pitch"], "\"With the kids in the back, you'll want this one.\"", [&"family"], [], []],
	[[&"player_pitch"], "\"Before you ask: yes, this one comes with paperwork.\"", [&"karen"], [], []],
	[[&"player_pitch"], "\"And before you ask, nobody else offers this one.\"", [&"hawk"], [], []],
	[[&"player_pitch"], "\"I've got the full terms on this if you want them.\"", [&"tech"], [], []],
	[[&"player_pitch"], "\"Thirty seconds, I promise. Check this out.\"", [&"kicker"], [], []],
	[[&"player_pitch"], "\"You're going to love this one.\"", [&"easygoing"], [], []],
	[[&"player_pitch"], "\"You're going to want this one, trust me.\"", [&"laydown"], [], []],
	[[&"player_pitch"], "\"Let's talk about what happens if the car gets totaled.\"", [], [&"gap"], []],
	[[&"player_pitch"], "\"How long were you planning to keep this car?\"", [], [&"vsc"], []],
	[[&"player_pitch"], "\"Do you park on the street at all?\"", [], [&"theft"], []],
	[[&"player_pitch"], "\"Planning to trade this one in someday?\"", [], [&"tvp"], []],
	[[&"player_pitch"], "\"You want it looking showroom-new for years, right?\"", [], [&"appearance"], []],
	[[&"player_pitch"], "\"How secure would you say your job is? Just curious.\"", [], [&"ppp"], []],
	[[&"player_pitch"], "\"How would you like to never sit in a waiting room again?\"", [], [&"concierge"], []],
	[[&"player_pitch"], "\"Ever had a month where the budget just didn't stretch?\"", [], [&"flex"], []],
	[[&"player_pitch"], "\"Do you ever tow anything? Boat? Trailer? Small house?\"", [], [&"perf"], []],
	[[&"player_pitch"], "\"Let me tell you about our WALKAWAY program.\"", [], [&"wap"], []],
	[[&"player_pitch"], "\"This one pairs really nicely with WALKAWAY.\"", [], [&"tlp"], []],


	# player_empathize: Acknowledge & Empathize (the card that was Explain the
	# Product). Acknowledge the worry; never tell them they're wrong.
	[[&"player_empathize"], "\"I hear you. That's a really fair concern.\"", [], [], []],
	[[&"player_empathize"], "\"Totally understand where you're coming from.\"", [], [], []],
	[[&"player_empathize"], "\"That makes complete sense.\"", [], [], []],
	[[&"player_empathize"], "\"I'd feel the same way in your shoes.\"", [], [], []],
	[[&"player_empathize"], "\"Lots of people feel that way at first.\"", [], [], []],
	[[&"player_empathize"], "\"Honestly? That's a smart thing to ask about.\"", [], [], []],
	[[&"player_empathize"], "\"You're not the first to say that, believe me.\"", [], [], []],
	[[&"player_empathize"], "\"That's completely understandable.\"", [], [], []],
	[[&"player_empathize"], "\"I appreciate you being straight with me.\"", [], [], []],
	[[&"player_empathize"], "\"Fair enough. I'd want to know that too.\"", [], [], []],
	[[&"player_empathize"], "\"No, I get it. It's a big decision.\"", [], [], []],
	[[&"player_empathize"], "\"Good. I'd rather you ask than wonder.\"", [], [], []],
	[[&"player_empathize"], "\"I'll go slowly. And yes, it's all in writing.\"", [&"karen"], [], []],
	[[&"player_empathize"], "\"I know your time matters. I'll keep it short.\"", [&"kicker"], [], []],
	[[&"player_empathize"], "\"With the kids, I get why every dollar counts.\"", [&"family"], [], []],
	[[&"player_empathize"], "\"I respect that. You know what you want.\"", [&"hawk"], [], []],
	[[&"player_empathize"], "\"Good question. You clearly did your homework.\"", [&"tech"], [], []],
	[[&"player_empathize"], "\"I hear you. No pressure at all.\"", [&"easygoing"], [], []],
	[[&"player_empathize"], "\"Don't worry, I'll walk you through all of it.\"", [&"laydown"], [], []],

	# player_clarify: Ask Clarifying Questions (was Hard Close). Flush out
	# whether it's the cost or the coverage.

	# player_relate: Keep It Relatable (was Coffee Framing).
	[[&"player_relate"], "\"That's just three cups of coffee a day!\"", [], [], []],
	[[&"player_relate"], "\"Break it down per day and it's pocket change.\"", [], [], []],
	[[&"player_relate"], "\"Skip one latte a week and it pays for itself.\"", [], [], []],
	[[&"player_relate"], "\"That's less than your streaming subscriptions.\"", [], [], []],
	[[&"player_relate"], "\"It's cheaper than a sandwich. A small sandwich.\"", [], [], []],
	[[&"player_relate"], "\"Think of it like a seatbelt for your wallet.\"", [], [], []],
	[[&"player_relate"], "\"It's like a warranty, but for you.\"", [], [], []],
	[[&"player_relate"], "\"It's like your phone case. Cheap next to the phone.\"", [], [], []],
	[[&"player_relate"], "\"You insure the house. This is the same idea.\"", [], [], []],
	[[&"player_relate"], "\"Think of it like a spare tire for your budget.\"", [], [], []],
	[[&"player_relate"], "\"Nobody buys an umbrella on a sunny day, right?\"", [], [], []],
	[[&"player_relate"], "\"Like a fire extinguisher. Boring, until it isn't.\"", [], [], []],
	[[&"player_relate"], "\"Okay, let me try explaining it a different way.\"", [], [], [&"COLD"]],
	[[&"player_relate"], "\"Do the math. Per day, it's basically nothing.\"", [&"hawk"], [], []],
	[[&"player_relate"], "\"Like a car seat. You hope it never matters.\"", [&"family"], [], []],
	[[&"player_relate"], "\"Think of it as a backup drive for your finances.\"", [&"tech"], [], []],
	[[&"player_relate"], "\"Short version: a seatbelt for your wallet.\"", [&"kicker"], [], []],

	# player_value: Back to Value (was Bundle It In) - and each product's own
	# value proposition, where one is written for it.
	[[&"player_value"], "\"Since we're already doing the other two...\"", [], [], []],
	[[&"player_value"], "\"Add it to the rest and the payment barely moves.\"", [], [], []],
	[[&"player_value"], "\"You've started the set. Might as well finish it.\"", [], [], []],
	[[&"player_value"], "\"Let me walk you through what this actually covers.\"", [], [], []],
	[[&"player_value"], "\"Here's the short version. No fine print. Well, some.\"", [], [], []],
	[[&"player_value"], "\"It's simple, really. Something goes wrong, you're covered.\"", [], [], []],
	[[&"player_value"], "\"Most people don't know this, but...\"", [], [], []],
	[[&"player_value"], "\"Peace of mind is the real product here.\"", [], [], []],
	[[&"player_value"], "\"For a few dollars, a lot of worry goes away.\"", [], [], []],
	[[&"player_value"], "\"This is the part people thank me for later.\"", [], [], []],
	[[&"player_value"], "\"It protects the investment you just made.\"", [], [], []],
	[[&"player_value"], "\"Small cost now, a big save if anything happens.\"", [], [], []],
	[[&"player_value"], "\"And honestly? It pretty much sells itself.\"", [], [], [&"ALMOST"]],
	[[&"player_value"], "\"One package, and the whole family's covered.\"", [&"family"], [], []],
	[[&"player_value"], "\"I can pull up the full contract if you want the details.\"", [&"tech"], [], []],
	[[&"player_value"], "\"Real quick, the thirty-second version...\"", [&"kicker"], [], []],
	[[&"player_value"], "\"Do the math on one bad day. It pays for itself.\"", [&"hawk"], [], []],
	[[&"player_value"], "\"And it's all in writing, start to finish.\"", [&"karen"], [], []],
	[[&"player_value"], "\"If the car's totaled, GAP pays off what insurance won't.\"", [], [&"gap"], []],
	[[&"player_value"], "\"When the factory warranty ends, this pays the repair bills.\"", [], [&"vsc"], []],
	[[&"player_value"], "\"We etch the glass, track the car, and replace lost keys.\"", [], [&"theft"], []],
	[[&"player_value"], "\"It locks in a floor on your trade-in. No nasty surprises.\"", [], [&"tvp"], []],
	[[&"player_value"], "\"Ceramic coat, tint, wheel care. It stays new for years.\"", [], [&"appearance"], []],
	[[&"player_value"], "\"Lose your job or get hurt, and this makes the payments.\"", [], [&"ppp"], []],
	[[&"player_value"], "\"We pick it up, leave you a loaner, bring it back fixed.\"", [], [&"concierge"], []],
	[[&"player_value"], "\"Skip a payment when money is tight. No questions asked.\"", [], [&"flex"], []],
	[[&"player_value"], "\"Tow package, winter traction, and a badge that says so.\"", [], [&"perf"], []],
	[[&"player_value"], "\"Life happens. WALKAWAY covers the big 'what ifs.'\"", [], [&"wap"], []],
	[[&"player_value"], "\"Fire, theft or a wreck: it covers what the payout misses.\"", [], [&"tlp"], []],

	# player_budget: Budget Options (was Offer a Discount) - "we have different
	# options to suit different budgets."
	[[&"player_budget"], "\"We have options to suit different budgets.\"", [], [], []],
	[[&"player_budget"], "\"There's a lighter plan that still covers the basics.\"", [], [], []],
	[[&"player_budget"], "\"Okay, let me see what I can do here.\"", [], [], []],
	[[&"player_budget"], "\"Tell you what, I'll sharpen my pencil.\"", [], [], []],
	[[&"player_budget"], "\"...but that's the best I can do!\"", [], [], []],
	[[&"player_budget"], "\"Don't tell my manager, but...\"", [], [], []],
	[[&"player_budget"], "\"Let's find a version that fits your number.\"", [], [], []],
	[[&"player_budget"], "\"We can trim it down and keep the important part.\"", [], [], []],
	[[&"player_budget"], "\"I can stretch the term so the payment stays put.\"", [], [], []],
	[[&"player_budget"], "\"Tell me the number, and I'll build around it.\"", [], [], []],
	[[&"player_budget"], "\"Alright, how does THIS number look?\"", [], [], [&"COLD"]],
	[[&"player_budget"], "\"Fine, fine. You drive a hard bargain.\"", [&"hawk"], [], []],
	[[&"player_budget"], "\"Fine. Here's my best number. Really.\"", [&"hawk"], [], []],
	[[&"player_budget"], "\"Since you've been SO patient with me...\"", [&"karen"], [], []],
	[[&"player_budget"], "\"You've been great, so let me knock a bit off.\"", [&"easygoing"], [], []],

	[[&"player_fearmonger"], "\"I had a customer last week who skipped this. Poor guy.\"", [], [], []],
	[[&"player_fearmonger"], "\"You know what a new transmission costs these days?\"", [], [], []],
	[[&"player_fearmonger"], "\"It won't happen to you. That's what my cousin said.\"", [], [], []],
	[[&"player_fearmonger"], "\"Picture it: 2 a.m., side of the highway, no coverage.\"", [], [], []],
	[[&"player_fearmonger"], "\"Nobody plans for the worst day of their life.\"", [], [], []],
	[[&"player_fearmonger"], "\"It's all fun and games until the tow truck shows up.\"", [], [], []],
	[[&"player_fearmonger"], "\"Picture the kids, stuck on the highway at night.\"", [&"family"], [], []],
	[[&"player_fearmonger"], "\"Total it, and you're still paying for it. For years.\"", [], [&"gap"], []],
	[[&"player_fearmonger"], "\"Cars around here vanish overnight. I've seen it.\"", [], [&"theft"], []],
	[[&"player_fearmonger"], "\"One sensor on these costs more than your rent.\"", [], [&"vsc"], []],
	[[&"player_fearmonger"], "\"Nobody expects the layoff. Nobody.\"", [], [&"ppp"], []],
	[[&"player_fearmonger"], "\"One winter of road salt. That's all it takes.\"", [], [&"appearance"], []],

	[[&"player_pad"], "\"There's just a small admin fee on top.\"", [], [], []],
	[[&"player_pad"], "\"That number includes a few little extras.\"", [], [], []],
	[[&"player_pad"], "\"Standard processing. You'll find that everywhere.\"", [], [], []],
	[[&"player_pad"], "\"Let me just tidy these numbers up for you.\"", [], [], []],
	[[&"player_pad"], "\"Don't worry about that line. Everybody pays that.\"", [], [], []],
	[[&"player_pad"], "\"And a little extra here. You won't even notice.\"", [&"laydown"], [], []],

	# player_listen: Active Listening (was Read the Room). Stay calm and
	# curious, and let them talk.

	# player_guide: The Program Guide (was Check Your Notes).
	[[&"player_guide"], "\"Uh... let me just check the Program Guide...\"", [], [], []],
	[[&"player_guide"], "\"Bear with me, it's all in the Program Guide.\"", [], [], []],
	[[&"player_guide"], "\"Hold on, let me look that up real quick.\"", [], [], []],
	[[&"player_guide"], "\"It's on the tip of my tongue...\"", [], [], []],
	[[&"player_guide"], "\"Where did I put that brochure...\"", [], [], []],
	[[&"player_guide"], "\"One sec, the Program Guide has a page on this.\"", [], [], []],
	[[&"player_guide"], "\"Let me find the exact wording for you.\"", [], [], []],
	[[&"player_guide"], "\"Page six... no, seven. Here it is.\"", [], [], []],

	[[&"player_comp"], "\"Good news, everyone! A year of WALKAWAY, on the house!\"", [], [], []],
	[[&"player_comp"], "\"Today only, everyone gets a free year of protection!\"", [], [], []],
	[[&"player_comp"], "\"Consider it a gift from the dealership.\"", [], [], []],
	[[&"player_comp"], "\"It's on us. No, really. Free.\"", [], [], []],

	[[&"player_justthething"], "\"Oh, I have just the product for you!\"", [], [], []],
	[[&"player_justthething"], "\"Wait, wait. I know exactly what you need.\"", [], [], []],
	[[&"player_justthething"], "\"You know what? I've got the perfect thing.\"", [], [], []],
	[[&"player_justthething"], "\"Say no more. I've got just the thing.\"", [], [], []],

	[[&"player_rightword"], "\"I know I have a word track for this...\"", [], [], []],
	[[&"player_rightword"], "\"Let me put it this way...\"", [], [], []],
	[[&"player_rightword"], "\"Okay, here's how I explain it to my own mother.\"", [], [], []],
	[[&"player_rightword"], "\"You know what they say about peace of mind...\"", [], [], []],

	[[&"player_smile"], "\"Hi! So glad you're here!\"", [], [], []],
	[[&"player_smile"], "\"Welcome, welcome! Make yourself comfortable.\"", [], [], []],
	[[&"player_smile"], "\"Big day! Congratulations on the new ride!\"", [], [], []],
	[[&"player_smile"], "\"You're going to love this car. I just know it.\"", [], [], []],
	[[&"player_smile"], "\"Isn't this exciting?\"", [], [], []],
	[[&"player_smile"], "\"So lovely to see you. Truly.\"", [&"karen"], [], []],

	[[&"player_jazz"], "\"Let me just put a little music on.\"", [], [], []],
	[[&"player_jazz"], "\"Anybody mind a little smooth jazz?\"", [], [], []],
	[[&"player_jazz"], "\"Ah, saxophone. Instantly calming, isn't it?\"", [], [], []],
	[[&"player_jazz"], "\"Everybody just breathe. Enjoy the tunes.\"", [], [], []],

	# player_close: the trial close, said by offer() itself as you ask.
	[[&"player_close"], "\"So, shall I add it in?\"", [], [], []],
	[[&"player_close"], "\"Can you see how that'd be worth it?\"", [], [], []],
	[[&"player_close"], "\"Should we put you down for it?\"", [], [], []],
	[[&"player_close"], "\"Sound good? Let's get you protected.\"", [], [], []],
	[[&"player_close"], "\"Sign here, here, and initial here.\"", [], [], []],
	[[&"player_close"], "\"Shall I put that in the paperwork?\"", [], [], []],
	[[&"player_close"], "\"Ready to add it?\"", [], [], []],
	[[&"player_close"], "\"So, are we protecting you?\"", [], [], []],
	[[&"player_close"], "\"Want me to include it today?\"", [], [], []],
	[[&"player_close"], "\"Can I go ahead and add that?\"", [], [], []],
	[[&"player_close"], "\"Does that sound like something you'd want?\"", [], [], []],
	[[&"player_close"], "\"Should I make it part of the deal?\"", [], [], []],
	[[&"player_close"], "\"Quick yes, and you're out of here.\"", [&"kicker"], [], []],
	[[&"player_close"], "\"I'll put every word in writing. Shall we?\"", [&"karen"], [], []],

	# --------------------------------------------------------- THEIR SIDE
	# interested: said instead of an objection when the product you put down
	# already clears their Line - see Shift._object().
	[[&"interested"], "\"Oh, that actually sounds good.\"", [], [], []],
	[[&"interested"], "\"Okay, I like the sound of that.\"", [], [], []],
	[[&"interested"], "\"Huh. That's right up my alley.\"", [], [], []],
	[[&"interested"], "\"Oh, now that's interesting.\"", [], [], []],
	[[&"interested"], "\"Yeah, I could see that.\"", [], [], []],
	[[&"interested"], "\"That's exactly what I was hoping for.\"", [], [], []],
	[[&"interested"], "\"Finally, something sensible.\"", [&"karen"], [], []],
	[[&"interested"], "\"Hm. Not bad. Not bad at all.\"", [&"hawk"], [], []],

	# reply_*: their answer to one of the method's techniques, where nothing
	# was written for the objection they have open (or none is).
	[[&"reply_empathize"], "\"Thanks. I appreciate that.\"", [], [], []],
	[[&"reply_empathize"], "\"Okay. I'm listening.\"", [], [], []],
	[[&"reply_empathize"], "\"That's fair, I guess.\"", [], [], []],
	[[&"reply_empathize"], "\"Thank you. That helps.\"", [], [], []],
	[[&"reply_empathize"], "\"At least you get it.\"", [], [], []],
	[[&"reply_empathize"], "\"Okay. Go on.\"", [], [], []],
	[[&"reply_empathize"], "\"That's... actually nice to hear.\"", [], [], []],
	[[&"reply_empathize"], "\"Well, finally someone understands.\"", [&"karen"], [], []],
	[[&"reply_empathize"], "\"Fine. But I'm still watching the number.\"", [&"hawk"], [], []],
	[[&"reply_clarify"], "\"Honestly? I'm not sure.\"", [], [], []],
	[[&"reply_clarify"], "\"It's just a lot to think about.\"", [], [], []],
	[[&"reply_clarify"], "\"Do I have to answer all these questions?\"", [], [], []],
	[[&"reply_clarify"], "\"Hm. Good question.\"", [], [], []],
	[[&"reply_clarify"], "\"Let me think about that.\"", [], [], []],
	[[&"reply_clarify"], "\"I guess it's mostly the money.\"", [], [], []],
	[[&"reply_clarify"], "\"I'm just not sure I need it.\"", [], [], []],
	[[&"reply_clarify"], "\"Why do you need to know that?\"", [&"karen"], [], []],
	[[&"reply_clarify"], "\"Can we skip the questions?\"", [&"kicker"], [], []],
	[[&"reply_clarify"], "\"Depends. What are the exact terms?\"", [&"tech"], [], []],
	[[&"reply_relate"], "\"Ha. Fair enough.\"", [], [], []],
	[[&"reply_relate"], "\"Okay, that makes it easier to picture.\"", [], [], []],
	[[&"reply_relate"], "\"I do drink a lot of coffee.\"", [], [], []],
	[[&"reply_relate"], "\"Ha. I never thought of it like that.\"", [], [], []],
	[[&"reply_relate"], "\"Okay, okay. I see what you mean.\"", [], [], []],
	[[&"reply_relate"], "\"That's a weird way to put it, but sure.\"", [], [], []],
	[[&"reply_relate"], "\"Car seats, yeah. That makes sense.\"", [&"family"], [], []],
	[[&"reply_value"], "\"Huh. When you put it that way...\"", [], [], []],
	[[&"reply_value"], "\"Okay, that's worth something.\"", [], [], []],
	[[&"reply_value"], "\"Alright, that's a fair point.\"", [], [], []],
	[[&"reply_value"], "\"Okay. I can see the use.\"", [], [], []],
	[[&"reply_value"], "\"Hm. That does sound useful.\"", [], [], []],
	[[&"reply_value"], "\"You're making a decent case.\"", [], [], []],
	[[&"reply_value"], "\"Still sounds pricey. But okay.\"", [&"hawk"], [], []],
	[[&"reply_budget"], "\"Okay, that's more like it.\"", [], [], []],
	[[&"reply_budget"], "\"Better. Keep going.\"", [], [], []],
	[[&"reply_budget"], "\"Okay, that I can work with.\"", [], [], []],
	[[&"reply_budget"], "\"That's closer to what I had in mind.\"", [], [], []],
	[[&"reply_budget"], "\"That's the least you could do.\"", [&"karen"], [], []],
	[[&"reply_listen"], "\"Honestly, I just want something reliable.\"", [], [], []],
	[[&"reply_listen"], "\"I just don't want any surprises.\"", [], [], []],
	[[&"reply_listen"], "\"Mostly I just want it to last.\"", [], [], []],
	[[&"reply_listen"], "\"I worry about the payments, honestly.\"", [], [], []],
	[[&"reply_listen"], "\"I had a bad experience last time.\"", [], [], []],
	[[&"reply_listen"], "\"I just want to understand what I'm buying.\"", [], [], []],
	[[&"reply_listen"], "\"We've got a baby on the way, so...\"", [&"family"], [], []],
	[[&"reply_listen"], "\"I've read every review of this car. Twice.\"", [&"tech"], [], []],
	[[&"reply_listen"], "\"I just want this done today.\"", [&"kicker"], [], []],
	[[&"reply_listen"], "\"Honestly? I'm happy either way.\"", [&"easygoing"], [], []],
	[[&"reply_listen"], "\"Whatever you think is best, really.\"", [&"laydown"], [], []],
]

# ------------------------------------------------------------- EXCHANGES
# A line of yours and the answers written for IT - so "Love the jacket" is
# never answered with something about the parking lot. Each line here gets a
# key (DialogueLine.key) and its replies answer only that key; a line with no
# reply that fits the customer is met with silence, not a non sequitur.
#
# [your tag, their tag, your line, your archetype_ids, replies], each reply
# [text] or [text, archetype_ids].
const EXCHANGES := [
	# Small Talk.
	[&"player_smalltalk", &"patience", "\"So, how was the drive in? Traffic behave itself?\"", [], [
		["\"Hah! The 401 was a parking lot this morning.\""],
		["\"Not bad, actually. Green lights all the way.\""],
		["\"That is nice, but I really do need to go soon.\"", [&"kicker"]]]],
	[&"player_smalltalk", &"patience", "\"Crazy weather we're having, huh?\"", [], [
		["\"Tell me about it. I forgot my umbrella.\""],
		["\"I'll take it over snow.\""]]],
	[&"player_smalltalk", &"patience", "\"Any big plans for the weekend?\"", [], [
		["\"My daughter has a game, actually.\""],
		["\"Just sleeping in, hopefully.\""],
		["\"Soccer, swimming, and a birthday party. Send help.\"", [&"family"]]]],
	[&"player_smalltalk", &"patience", "\"Can I get you a coffee? It's terrible, but it's free.\"", [], [
		["\"Ha. Free and terrible? Sure.\""],
		["\"I'm good, thanks. Already had three.\""],
		["\"Is it at least fresh?\"", [&"karen"]],
		["\"No time for coffee, thanks.\"", [&"kicker"]]]],
	[&"player_smalltalk", &"patience", "\"So what do you do for work?\"", [], [
		["\"Accounting. Don't get too excited.\""],
		["\"Nursing. Long shifts.\""],
		["\"Software. Please don't ask me to fix your printer.\"", [&"tech"]]]],
	[&"player_smalltalk", &"patience", "\"Did you catch the game last night?\"", [], [
		["\"Don't remind me.\""],
		["\"Fell asleep in the third period.\""],
		["\"No time for games. Literally.\"", [&"kicker"]]]],
	[&"player_smalltalk", &"patience", "\"Love the jacket, by the way. Where's it from?\"", [], [
		["\"Oh, thanks! It was on sale.\""],
		["\"This old thing? Thank you.\""],
		["\"It's designer, actually.\"", [&"karen"]]]],
	[&"player_smalltalk", &"patience", "\"Parking okay out there? That lot is a maze.\"", [], [
		["\"Took me two laps to find a spot.\""],
		["\"Found one right by the door, for once.\""],
		["\"Which is why I'd like to be out soon.\"", [&"kicker"]]]],
	[&"player_smalltalk", &"patience", "\"How old are the kids? Mine just started school.\"", [&"family"], [
		["\"Six and nine. Send help.\""],
		["\"The baby's due in March!\""]]],
	[&"player_smalltalk", &"patience", "\"The kids doing okay? There are lollipops at the desk.\"", [&"family"], [
		["\"Oh, they'll love that. Thanks.\""],
		["\"Please don't. They've had enough sugar.\""]]],
	[&"player_smalltalk", &"patience", "\"Can I get you anything? Water? A manager?\"", [&"karen"], [
		["\"Water. I'll let you know about the manager.\""],
		["\"Just get on with it, please.\""]]],
	[&"player_smalltalk", &"patience", "\"I'll keep this quick, I promise.\"", [&"kicker"], [
		["\"I'll believe it when I see it.\""],
		["\"Good. I have somewhere to be.\""]]],
	[&"player_smalltalk", &"patience", "\"You must have done a ton of research on this one.\"", [&"tech"], [
		["\"Forty-two browser tabs. At least.\""],
		["\"I've read every review there is.\""]]],
	[&"player_smalltalk", &"patience", "\"Bet you shopped around a bit before coming here, huh?\"", [&"hawk"], [
		["\"Three dealers. You're the fourth.\""],
		["\"Of course. I'm not a rookie.\""]]],
	[&"player_smalltalk", &"patience", "\"Beautiful day to buy a car, isn't it?\"", [&"easygoing"], [
		["\"Isn't it? I'm in a great mood.\""],
		["\"Couldn't ask for better.\""]]],
	[&"player_smalltalk", &"patience", "\"You look like you could use a coffee. Long day?\"", [&"laydown"], [
		["\"So long. Yes, please.\""],
		["\"Is it that obvious?\""]]],

	# Ask Clarifying Questions, with nothing open to ask about: a question
	# deserves its own answer.
	[&"player_clarify", &"reply_clarify", "\"What matters most to you in all this?\"", [], [
		["\"Honestly? Keeping the payment down.\""],
		["\"Not getting stuck with surprises.\""],
		["\"The kids being safe.\"", [&"family"]],
		["\"Why do you need to know that?\"", [&"karen"]]]],
	[&"player_clarify", &"reply_clarify", "\"Can I ask what's giving you pause?\"", [], [
		["\"It's just a lot of money.\""],
		["\"I'm not sure I'd use it.\""],
		["\"Can we skip the questions?\"", [&"kicker"]]]],
	[&"player_clarify", &"reply_clarify", "\"Is it the price, or the coverage itself?\"", [], [
		["\"The price, mostly.\""],
		["\"Bit of both, honestly.\""],
		["\"Depends. What are the exact terms?\"", [&"tech"]]]],
	[&"player_clarify", &"reply_clarify", "\"Just so I understand, what's the hesitation?\"", [], [
		["\"I don't like add-ons.\""],
		["\"I just need to think about it.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Help me understand. What's the part that bugs you?\"", [], [
		["\"The monthly number.\""],
		["\"All the fine print.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Is it the monthly number, or the total?\"", [], [
		["\"The monthly.\""],
		["\"The total, honestly.\""]]],
	[&"player_clarify", &"reply_clarify", "\"What would make this a yes for you?\"", [], [
		["\"A lower price.\""],
		["\"Knowing I'd actually use it.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Have you had something like this before?\"", [], [
		["\"Once. Never used it.\""],
		["\"No, first time.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Is that a 'not now', or a 'not ever'?\"", [], [
		["\"Probably not now.\""],
		["\"Ha. Not ever, maybe.\""]]],
	[&"player_clarify", &"reply_clarify", "\"What's your biggest worry about owning the car?\"", [], [
		["\"Repairs, honestly.\""],
		["\"Getting stuck with the payments.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Quick question, then I'll let you go.\"", [&"kicker"], [
		["\"Fine. Quick.\""],
		["\"Go ahead. Fast.\""]]],
	[&"player_clarify", &"reply_clarify", "\"How many years were you planning to keep it?\"", [&"tech"], [
		["\"Ten, if it lasts.\""],
		["\"Five, then I upgrade.\""]]],
	[&"player_clarify", &"reply_clarify", "\"What number did you have in your head?\"", [&"hawk"], [
		["\"Lower than that.\""],
		["\"Zero, ideally.\""]]],
	[&"player_clarify", &"reply_clarify", "\"What would you expect to get for that price?\"", [&"karen"], [
		["\"Everything. In writing.\""],
		["\"A lot more than this.\""]]],
	[&"player_clarify", &"reply_clarify", "\"Who else will be driving the car?\"", [&"family"], [
		["\"My partner, and soon our teenager.\""],
		["\"Just me and my spouse.\""]]],

	# Active Listening, with nothing open: you ask, they open up.
	[&"player_listen", &"reply_listen", "\"Mm-hm. Go on.\"", [], [
		["\"I just want something reliable.\""],
		["\"I just don't want any surprises.\""]]],
	[&"player_listen", &"reply_listen", "\"Tell me more about that.\"", [], [
		["\"Well, my last car was a lemon.\""],
		["\"I had a bad experience last time.\""]]],
	[&"player_listen", &"reply_listen", "\"Take your time. I'm listening.\"", [], [
		["\"Thanks. It's a lot to take in.\""],
		["\"I appreciate that.\""],
		["\"I just want this done today.\"", [&"kicker"]]]],
	[&"player_listen", &"reply_listen", "\"So what matters most to you here?\"", [], [
		["\"Keeping it running for years.\""],
		["\"A payment I can live with.\""],
		["\"Honestly? I'm happy either way.\"", [&"easygoing"]]]],
	[&"player_listen", &"reply_listen", "\"What brings you in today, really?\"", [], [
		["\"The old car finally died.\""],
		["\"We need something bigger.\""],
		["\"We've got a baby on the way, so...\"", [&"family"]],
		["\"I've read every review of this car. Twice.\"", [&"tech"]]]],
	[&"player_listen", &"reply_listen", "\"Interesting. Tell me why that matters to you.\"", [], [
		["\"I've been burned before.\""],
		["\"I just like knowing I'm covered.\""]]],
	[&"player_listen", &"reply_listen", "\"Okay. What else is on your mind?\"", [], [
		["\"Honestly, the payments.\""],
		["\"Whether I'm overpaying.\""],
		["\"Whatever you think is best, really.\"", [&"laydown"]]]],
	[&"player_listen", &"reply_listen", "\"Walk me through what you're picturing.\"", [], [
		["\"Something that lasts.\""],
		["\"No surprise bills, ever.\""]]],
	[&"player_listen", &"reply_listen", "\"And what would the perfect deal look like?\"", [], [
		["\"Cheap and worry-free.\""],
		["\"Ha. Free.\""]]],
	[&"player_listen", &"reply_listen", "\"Got it. Anything else I should know?\"", [], [
		["\"I'm on a tight budget.\""],
		["\"I drive a lot for work.\""]]],
	[&"player_listen", &"reply_listen", "\"Go ahead. I'm all ears. Truly.\"", [&"karen"], [
		["\"Good. Because I have a list.\""],
		["\"Finally, someone who listens.\""]]],
]

## Each of the method's techniques: [the tag your line goes in, the tag their
## answer goes in]. &"" for no answer - the guide is you looking something up,
## and the close is answered by the yes (accepted) or the no that follows it.
const TECHNIQUES := {
	"empathize": [&"player_empathize", &"reply_empathize"],
	"clarify": [&"player_clarify", &"reply_clarify"],
	"relate": [&"player_relate", &"reply_relate"],
	"value": [&"player_value", &"reply_value"],
	"budget": [&"player_budget", &"reply_budget"],
	"listen": [&"player_listen", &"reply_listen"],
	"guide": [&"player_guide", &""],
	"close": [&"player_close", &""],
}

# ------------------------------------------------------------- OBJECTIONS
# One entry per objection, laid out the way the deck lays them out.
#
# "raise" is how a customer brings it up: [the tag a product asks for in its
# objection_tags, rows], each row [text, archetype_ids, product_ids] with the
# last two optional - an archetype row is the deck's "getting ahead of
# objections": who tends to raise it. Saying any of them opens this objection.
# No "raise" means it is only ever flushed out of another.
#
# Each technique is [your lines, their answers]. Either side is a list of
# variants - say the same thing a different way, since any of yours can meet
# any of theirs - and either may be left out. An answer written as [text,
# objection] instead flushes out the real objection behind this one: "No
# thanks" turning out to be the price.
const OBJECTIONS := [
	# ---- WALKAWAY: the deck's own, condensed.
	{"id": &"walkaway_too_expensive",
		"raise": [&"objection_walkaway", [
			["\"It's too expensive.\""],
			["\"That's a lot to add to my payment.\""],
			["\"That's more than I wanted to spend.\""],
			["\"Another add-on? My payment's already high.\""],
			["\"Whoa. How much a month is that?\"", [&"hawk"]],
			["\"I'm not paying extra for that.\"", [&"karen"]],
		]],
		"clarify": [[
				"\"So you see the benefit, it's just more than you want to spend?\"",
				"\"So the coverage makes sense, it's just the price?\"",
				"\"You like what it does, just not the cost, right?\"",
			], ["\"Well, yeah.\"", "\"Yeah, basically.\"", "\"Pretty much, yeah.\""]],
		"empathize": [[
				"\"I can appreciate that. We have options for every budget.\"",
				"\"Totally fair. That's why there's more than one plan.\"",
				"\"I hear you. Let's find one that fits your budget.\"",
			], ["\"Okay. Like what?\"", "\"Okay. What else is there?\"", "\"Alright, show me.\""]],
		"budget": [[
				"\"Standard Plus 4 is great protection, under $7 a payment.\"",
				"\"Plus 4 covers four payments, for much less a month.\"",
				"\"There's a lighter plan, Standard Plus 4. Under $7.\"",
			], ["\"Under seven bucks? Huh.\"", "\"Seven bucks I can do.\"",
				"\"Okay, that's more reasonable.\""]],
		"relate": [[
				"\"Would 4 months get you back on your feet, or a full year?\"",
				"\"Four months is a cushion. A year is peace of mind.\"",
				"\"Could you get back on your feet in four months?\"",
			], ["\"A full year would be nice.\"", "\"Four months... maybe?\"",
				"\"A year sounds safer, honestly.\""]],
		"value": [[
				"\"A full year of payments covered, for a few dollars more.\"",
				"\"The full plan covers twelve payments, not four.\"",
				"\"For a few dollars more, the whole year is covered.\"",
			], ["\"When you put it like that...\"", "\"Twelve, huh?\"",
				"\"That's a big difference.\""]],
		"listen": [[
				"\"What were you hoping to keep the payment at?\"",
				"\"What number feels comfortable for you?\"",
				"\"Is there a payment you won't go over?\"",
			], ["\"Somewhere under five hundred.\"", "\"I'd like to stay under five hundred.\"",
				"\"Under five hundred, if I can.\""]],
		"guide": [["\"It says here Plus 4 covers 4 payments instead of 12.\""]],
		"close": [["\"Four months covered, or the whole year?\"",
			"\"Plus 4 or the full year, which feels right?\"",
			"\"Shall we start you on Plus 4?\""]],
	},
	{"id": &"walkaway_no_thanks",
		"raise": [&"objection_walkaway", [
			["\"No thanks.\""],
			["\"I think I'll pass.\""],
			["\"I'm good, thanks.\""],
			["\"Not for me, thanks.\""],
			["\"No thanks. Can we wrap this up?\"", [&"kicker"]],
			["\"No. Absolutely not.\"", [&"karen"]],
		]],
		"clarify": [[
				"\"Is it the payment, or you don't see yourself using it?\"",
				"\"Can I ask, is it the cost or the coverage?\"",
				"\"Is it the price, or you don't think you'd use it?\"",
			], [
				["\"Honestly? It's the payment.\"", &"walkaway_too_expensive"],
				["\"The cost, mostly.\"", &"walkaway_too_expensive"],
				["\"I just don't see myself needing it.\"", &"walkaway_dont_need"],
				["\"I don't think I'd ever need it.\"", &"walkaway_dont_need"],
			]],
		"listen": [[
				"\"No pressure. What's making you hesitate?\"",
				"\"Totally fine. What's your hesitation?\"",
				"\"No problem. What's on your mind?\"",
			], [
				["\"It's the money, mostly.\"", &"walkaway_too_expensive"],
				["\"It's just more money.\"", &"walkaway_too_expensive"],
				["\"I don't think I'd ever use it.\"", &"walkaway_dont_need"],
				["\"I can't see myself using it.\"", &"walkaway_dont_need"],
			]],
		"empathize": [[
				"\"No problem at all. Most people say that at first.\"",
				"\"Fair enough. Can I ask one quick thing?\"",
				"\"No worries. Most people need a minute.\"",
			], ["\"Yeah, I'm just not sure.\"", "\"Sure, go ahead.\"", "\"I guess.\""]],
		"guide": [["\"Can I show you one page of the Program Guide? It's quick.\"",
			"\"The guide covers the what, why and how. Quick look?\""]],
	},
	{"id": &"walkaway_dont_need",
		"raise": [&"objection_walkaway", [
			["\"I don't think I need it.\""],
			["\"I don't see myself using it.\""],
			["\"I've never needed anything like that.\""],
			["\"I'm healthy and my job's solid.\""],
			["\"Ah, I don't think I'll ever need that.\"", [&"easygoing"]],
		]],
		"clarify": [[
				"\"Because you won't get sick or laid off, or you have a plan?\"",
				"\"Is that because you won't need it, or you'd manage?\"",
				"\"Do you have a plan in place if something happened?\"",
			], ["\"I just don't see it happening.\"", "\"I'd figure something out.\"",
				"\"Not really, I guess.\""]],
		"empathize": [[
				"\"Totally understand, and hopefully you never do.\"",
				"\"I hope you never do. Truly.\"",
				"\"I get it. Nobody plans on bad luck.\"",
			], ["\"Right. Exactly.\"", "\"Thanks. Me neither.\"", "\"Exactly.\""]],
		"relate": [[
				"\"It's like a car warranty. Built well, but you never know.\"",
				"\"Cars come with a warranty for a reason.\"",
				"\"You'd never drive off without a warranty, right?\"",
			], ["\"Huh. I guess that's fair.\"", "\"No, I guess not.\"", "\"Fair point.\""]],
		"value": [[
				"\"That's why most clients like a warranty for themselves.\"",
				"\"It's a few dollars to cover your biggest bill.\"",
				"\"It covers your payments if life gets in the way.\"",
			], ["\"A warranty for me. Okay.\"", "\"That would help, I guess.\"",
				"\"Hm. My biggest bill, sure.\""]],
		"listen": [[
				"\"If you lost your job, how would you make the payments?\"",
				"\"If something did happen, how would you pay the car?\"",
				"\"Say you got sick a while. How'd you cover payments?\"",
			], [
				["\"From my savings, I guess.\"", &"walkaway_savings"],
				["\"My savings would cover it.\"", &"walkaway_savings"],
				["\"I'd use my line of credit.\"", &"walkaway_line_of_credit"],
				["\"I'd put it on my credit line.\"", &"walkaway_line_of_credit"],
			]],
		"close": [["\"Can you see how that might be of value to you, too?\"",
			"\"Would a warranty for yourself be worth a few dollars?\"",
			"\"Shall we cover you, not just the car?\""]],
	},
	{"id": &"walkaway_savings",
		"empathize": [[
				"\"It's great you're in a position to do that.\"",
				"\"That's great planning on your part.\"",
				"\"Good for you. Most people can't.\"",
			], ["\"I've worked hard for it.\"", "\"It took a while.\"",
				"\"Thanks. It wasn't easy.\""]],
		"relate": [[
				"\"Savings are for the fun stuff, not the car payment.\"",
				"\"Your rainy-day fund shouldn't pay for the car.\"",
				"\"Savings should go to things you enjoy.\"",
			], ["\"...Fair point.\"", "\"Huh. True.\"", "\"I'd rather spend it on fun, sure.\""]],
		"value": [[
				"\"Most people like you protect their savings for something they want.\"",
				"\"For a few dollars, your savings stay untouched.\"",
				"\"This keeps your savings for what you really want.\"",
			], ["\"Like a trip, or the kids' school.\"", "\"Untouched sounds nice.\"",
				"\"That's a nice thought.\""]],
		"listen": [[
				"\"What are those savings for, ideally?\"",
				"\"What would you rather use those savings for?\"",
				"\"What are you saving up for?\"",
			], ["\"A rainy day. Maybe a trip.\"", "\"A trip, honestly.\"", "\"Retirement, mostly.\""]],
		"close": [["\"Wouldn't you rather keep those savings for yourself?\"",
			"\"Keep the savings, cover the payments. Deal?\"",
			"\"Shall we protect that nest egg?\""]],
	},
	{"id": &"walkaway_line_of_credit",
		"empathize": [[
				"\"Good to have that option.\"",
				"\"Smart to have one.\"",
				"\"That's a good safety net.\"",
			], ["\"It's there for emergencies.\"", "\"Yeah, just in case.\"",
				"\"I've never really used it.\""]],
		"relate": [[
				"\"If something happened, you'd need that credit for other bills.\"",
				"\"That credit line might need to cover other bills.\"",
				"\"If money's tight, that credit gets used up fast.\"",
			], ["\"Hm. I hadn't thought of that.\"", "\"Hm. Probably true.\"",
				"\"Yeah, it would go fast.\""]],
		"value": [[
				"\"For a few dollars, your biggest bill is taken care of.\"",
				"\"This keeps your credit line free for emergencies.\"",
				"\"It takes your biggest bill off the table.\"",
			], ["\"That would take some stress off.\"", "\"Off the table. I like that.\"",
				"\"That's fair.\""]],
		"listen": [[
				"\"What else is that line of credit there for?\"",
				"\"When did you last need that line of credit?\"",
				"\"What else would that credit have to cover?\"",
			], ["\"Emergencies, mostly.\"", "\"Car repairs, once.\"", "\"Bills, I guess.\""]],
		"close": [["\"Can you see why most people protect that line of credit?\"",
			"\"Shall we keep that credit for real emergencies?\"",
			"\"Want your car payment covered instead?\""]],
	},
	{"id": &"walkaway_work_coverage",
		"raise": [&"objection_walkaway", [
			["\"I have great coverage through work.\""],
			["\"My job has disability coverage.\""],
			["\"Work already covers me.\""],
			["\"My work benefits already cover all that.\"", [&"tech"]],
		]],
		"empathize": [[
				"\"That's great. Employers who care make a big difference.\"",
				"\"That's great. Not everybody gets that.\"",
				"\"Good benefits are worth a lot.\"",
			], ["\"Yeah, they're pretty good to us.\"", "\"Yeah, I'm lucky.\"",
				"\"It's a good company.\""]],
		"clarify": [[
				"\"To be blunt, the best plans I know pay only 67% on disability.\"",
				"\"Most plans only pay about two thirds of your pay.\"",
				"\"Did you know most work plans stop at two thirds of pay?\"",
			], ["\"Wait, only 67 percent?\"", "\"Only two thirds?\"", "\"I didn't, no.\""]],
		"relate": [[
				"\"I don't know about you, but I spend more than two thirds of my pay!\"",
				"\"Could you live on two thirds of your income?\"",
				"\"Two thirds of your pay, all your bills. Doable?\"",
			], ["\"Ha. Don't we all.\"", "\"That'd be tight.\"", "\"Not easily.\""]],
		"value": [[
				"\"WALKAWAY tops that up, on top of any other benefit you get.\"",
				"\"This sits on top of your work coverage.\"",
				"\"It fills the gap your work plan leaves.\"",
			], ["\"On top of it? Okay.\"", "\"So both would pay?\"", "\"Okay, that's helpful.\""]],
		"listen": [[
				"\"What does your plan at work actually pay?\"",
				"\"Have you ever read the fine print on that plan?\"",
				"\"How long does your work plan pay for?\"",
			], ["\"Most of my salary, I think?\"", "\"I just know I have it.\"",
				"\"I'm not actually sure.\""]],
		"close": [["\"Can you see how $15 for $25,000 of benefits could come in handy?\"",
			"\"Want to close that gap for about $15?\"",
			"\"Shall we top up what work gives you?\""]],
	},
	{"id": &"walkaway_lots_of_insurance",
		"raise": [&"objection_walkaway", [
			["\"I already have lots of insurance.\""],
			["\"I'm insured up to my eyeballs already.\""],
			["\"I have life insurance already.\""],
			["\"We already have life insurance for the kids.\"", [&"family"]],
		]],
		"empathize": [[
				"\"That's great news! It's always great to be protected.\"",
				"\"Smart. You clearly care about your family.\"",
				"\"Love that. You're well prepared.\"",
			], ["\"I like to be careful.\"", "\"I try to be.\"", "\"Thanks. I think so.\""]],
		"clarify": [[
				"\"Would that policy end up paying off the car?\"",
				"\"If something happened, would that policy pay the car?\"",
				"\"Would your family want that money going to a car?\"",
			], ["\"I mean... I guess it would.\"", "\"I suppose so.\"", "\"Not really, no.\""]],
		"value": [[
				"\"This keeps your life insurance from paying off the car.\"",
				"\"This pays off the car, so your policy goes to family.\"",
				"\"It keeps your life insurance for your loved ones.\"",
			], ["\"Huh. I never thought of that.\"", "\"Oh. That makes sense.\"",
				"\"So they keep it all?\""]],
		"relate": [[
				"\"That way, your loved ones keep more of that money.\"",
				"\"Your policy is for your family, not your lender.\"",
				"\"Leave your family money, not a car loan.\"",
			], ["\"That does matter to me.\"", "\"That's true.\"", "\"Hm. Fair.\""]],
		"listen": [[
				"\"Who is that policy meant to look after?\"",
				"\"What's that policy meant to cover?\"",
				"\"Who did you take that policy out for?\"",
			], ["\"My family, of course.\"", "\"The kids, mostly.\"", "\"My spouse.\""]],
		"close": [["\"Isn't a few dollars a solid way to protect that inheritance?\"",
			"\"Shall we keep that inheritance whole?\"",
			"\"Protect the policy for a few dollars?\""]],
	},
	{"id": &"walkaway_wont_qualify",
		"raise": [&"objection_walkaway", [
			["\"I wouldn't qualify for that.\""],
			["\"I'm too old for that kind of thing.\""],
			["\"With my health? No chance.\""],
			["\"I probably wouldn't even qualify.\"", [&"laydown"]],
		]],
		"empathize": [[
				"\"I hear that a lot. You'd be surprised.\"",
				"\"A lot of people think that. Let me check.\"",
				"\"I understand. Let's see, though.\"",
			], ["\"Would I, though?\"", "\"Go ahead, check.\"", "\"Okay...\""]],
		"clarify": [[
				"\"Everyone under 80 qualifies. No pre-existing condition clauses.\"",
				"\"Are you under 80? Then you qualify.\"",
				"\"No medical checks, no health questions. Really.\"",
			], ["\"Really? None at all?\"", "\"I'm under 80, yes.\"", "\"No checks at all?\""]],
		"value": [[
				"\"No good health statements, and no medical checks.\"",
				"\"No health statements. Nothing to fill out.\"",
				"\"It's built so nearly everyone can get it.\"",
			], ["\"Well, that's easy enough.\"", "\"That's a relief.\"",
				"\"Huh. Nearly everyone?\""]],
		"listen": [[
				"\"What makes you think you wouldn't?\"",
				"\"What makes you say that?\"",
				"\"Why do you think you wouldn't qualify?\"",
			], ["\"My health isn't the best.\"", "\"I've had some health issues.\"",
				"\"Just a hunch.\""]],
		"guide": [["\"It's right here in the Program Guide: no medical checks.\"",
			"\"The guide says it: under 80, and you're in.\"",
			"\"Right here: no pre-existing condition clauses.\""]],
		"close": [["\"So nothing's standing in your way. Shall we add it?\"",
			"\"Since you qualify, shall we add it?\"",
			"\"Nothing's stopping you. Want it?\""]],
	},
	{"id": &"walkaway_buy_outright",
		"raise": [&"objection_walkaway", [
			["\"I'd just buy the car outright.\""],
			["\"If it came to that, I'd just pay it off.\""],
			["\"I'd just use my savings if it came to it.\""],
			["\"I'd just pay the thing off in cash.\"", [&"hawk"]],
		]],
		"empathize": [[
				"\"That's a great position to be in. Fantastic flexibility.\"",
				"\"That's great. Not many people can say that.\"",
				"\"Love that kind of flexibility.\"",
			], ["\"I've been saving a while.\"", "\"Thanks, it took work.\"",
				"\"It's nice, yeah.\""]],
		"clarify": [[
				"\"Would you rather spend those savings, or keep them?\"",
				"\"Would you want to drain your savings in a crisis?\"",
				"\"Is that money you'd rather keep?\"",
			], ["\"Keep them, obviously.\"", "\"Not really, no.\"", "\"I'd rather keep it.\""]],
		"value": [[
				"\"Many in your spot keep their savings intact for hard times.\"",
				"\"This keeps your investments working for you.\"",
				"\"Keep the cash, and let this cover the payments.\"",
			], ["\"I do like having a cushion.\"", "\"That's a good point.\"",
				"\"I like keeping my cash.\""]],
		"listen": [[
				"\"What would that do to your savings?\"",
				"\"What would those savings be for otherwise?\"",
				"\"How long did it take you to save that up?\"",
			], ["\"Put a dent in them, sure.\"", "\"Retirement.\"", "\"Years, honestly.\""]],
		"close": [["\"Would that kind of flexibility be of value to you too?\"",
			"\"Shall we keep your savings safe?\"",
			"\"Want that flexibility built in?\""]],
	},

	# ---- WALKAWAY GAP: the same method, paraphrased for the gap between the
	# loan and the payout.
	{"id": &"walkaway_gap_too_expensive",
		"raise": [&"objection_walkaway_gap", [
			["\"It's too expensive.\""],
			["\"That's a lot just for a 'what if.'\""],
			["\"Do I really need to pay for that?\""],
			["\"That's too much on top of everything.\""],
			["\"How much is THAT going to run me?\"", [&"hawk"]],
		]],
		"clarify": [[
				"\"So you like the idea, it's just the price?\"",
				"\"So you see the point, just not the price?\"",
				"\"The coverage makes sense, the cost doesn't?\"",
			], ["\"Pretty much.\"", "\"Basically.\"", "\"Yeah.\""]],
		"empathize": [[
				"\"Totally fair. Nobody wants a bigger payment.\"",
				"\"I get it. Payments add up fast.\"",
				"\"Fair. Nobody likes extra costs.\"",
			], ["\"No kidding.\"", "\"They sure do.\"", "\"Exactly.\""]],
		"relate": [[
				"\"It's less than a tank of gas a month.\"",
				"\"It's less than a takeout dinner each month.\"",
				"\"About one coffee a week.\"",
			], ["\"Huh. Really?\"", "\"Okay, that's not much.\"", "\"Huh. That's it?\""]],
		"value": [[
				"\"Total the car, and you won't be paying for one you lost.\"",
				"\"A total loss could cost you thousands.\"",
				"\"It saves you paying for a car you don't have.\"",
			], ["\"That would be awful.\"", "\"Thousands? Yikes.\"", "\"Yeah, no thanks.\""]],
		"budget": [[
				"\"Spread over the loan, it's a few dollars a payment.\"",
				"\"It's a few dollars a month, spread over the loan.\"",
				"\"Spread out, it barely moves your payment.\"",
			], ["\"Okay, that's not bad.\"", "\"Barely, huh?\"", "\"Okay, I can live with that.\""]],
		"listen": [[
				"\"Where were you hoping to keep the payment?\"",
				"\"What payment were you aiming for?\"",
			], ["\"As low as it'll go.\"", "\"Something reasonable.\""]],
		"close": [["\"Want that gap covered for a few dollars?\"",
			"\"Close that gap for a few dollars?\"",
			"\"Shall we add it?\""]],
	},
	{"id": &"walkaway_gap_insured",
		"raise": [&"objection_walkaway_gap", [
			["\"My car insurance covers that.\""],
			["\"That's what my insurance is for.\""],
			["\"I already pay for full coverage.\""],
			["\"Doesn't my insurance already cover that?\"", [&"tech"]],
		]],
		"empathize": [[
				"\"Good, you should have that.\"",
				"\"Smart. Full coverage is great.\"",
				"\"Good. You need that.\"",
			], ["\"Exactly.\"", "\"Right.\"", "\"Thanks.\""]],
		"clarify": [[
				"\"Insurance pays what the car's worth, not what you owe.\"",
				"\"Insurance pays the car's value, not your loan.\"",
				"\"If you owe more than it's worth, who pays the rest?\"",
			], ["\"Wait, those aren't the same?\"", "\"Wait, really?\"", "\"Hm. I would?\""]],
		"relate": [[
				"\"New cars lose value fast. Your loan doesn't.\"",
				"\"A new car loses value the day you drive it.\"",
				"\"Your loan shrinks slower than the car's value.\"",
			], ["\"Huh. Good point.\"", "\"Ugh. True.\"", "\"That's a good point.\""]],
		"value": [[
				"\"This covers the difference, so you don't pay off a car you lost.\"",
				"\"It covers what insurance won't.\"",
				"\"So you're never paying for a car you lost.\"",
			], ["\"Okay, that makes sense.\"", "\"That's worth having.\"", "\"Good to know.\""]],
		"listen": [[
				"\"And what would your insurance pay out, do you think?\"",
				"\"Do you know what your policy would pay out?\"",
				"\"Have you ever had a car written off before?\"",
			], ["\"What it's worth, I guess.\"", "\"Not really.\"", "\"No, thankfully.\""]],
		"close": [["\"Shall we close that gap?\"",
			"\"Want the gap covered too?\"",
			"\"Shall we cover what insurance won't?\""]],
	},
	{"id": &"walkaway_gap_dont_need",
		"raise": [&"objection_walkaway_gap", [
			["\"I'm not planning on wrecking it.\""],
			["\"I'm a careful driver.\""],
			["\"I've never been in an accident.\""],
			["\"Nothing's going to happen to it.\""],
		]],
		"clarify": [[
				"\"If it's ever totaled, how would you cover the rest of the loan?\"",
				"\"If it's stolen, would the payout cover your loan?\"",
				"\"What would you owe if it was written off?\"",
			], ["\"I... honestly don't know.\"", "\"I'm not sure.\"", "\"No idea, honestly.\""]],
		"listen": [[
				"\"What would you do if it was stolen tomorrow?\"",
				"\"And if it was written off, then what?\"",
			], [
				["\"Call my insurance, I guess?\"", &"walkaway_gap_insured"],
				["\"My insurance would cover it?\"", &"walkaway_gap_insured"],
			]],
		"empathize": [[
				"\"I'm sure you are. Hopefully you never need it.\"",
				"\"Great record. Hopefully it stays that way.\"",
				"\"I believe you. It's other drivers I worry about.\"",
			], ["\"I hope not.\"", "\"Me too.\"", "\"Ha. Fair.\""]],
		"relate": [[
				"\"Nobody plans it. That's why they call it an accident.\"",
				"\"You can be careful. The other guy might not be.\"",
				"\"Accidents aren't planned. That's the point.\"",
			], ["\"Ha. Fair enough.\"", "\"True enough.\"", "\"Okay, okay.\""]],
		"value": [[
				"\"Fire, theft or accident, the gap is covered.\"",
				"\"Fire, theft, or a wreck, you're covered either way.\"",
				"\"Even if it's not your fault, the gap is covered.\"",
			], ["\"Even theft? Huh.\"", "\"Even theft?\"", "\"Good to know.\""]],
		"close": [["\"Can you see how that might be worth a few dollars?\"",
			"\"Shall we cover the what-ifs?\"",
			"\"Want that protection?\""]],
	},
	{"id": &"walkaway_gap_no_thanks",
		"raise": [&"objection_walkaway_gap", [
			["\"No thanks.\""],
			["\"Not interested.\""],
			["\"I'll pass on that one.\""],
			["\"No. Absolutely not.\"", [&"karen"]],
		]],
		"clarify": [[
				"\"Is it the price, or you don't see yourself needing it?\"",
				"\"Is it the cost, or you'd never need it?\"",
			], [
				["\"It's the price.\"", &"walkaway_gap_too_expensive"],
				["\"The cost.\"", &"walkaway_gap_too_expensive"],
				["\"I just don't think I'll need it.\"", &"walkaway_gap_dont_need"],
				["\"I'd never need it.\"", &"walkaway_gap_dont_need"],
			]],
		"listen": [[
				"\"No pressure. What's holding you back?\"",
				"\"No problem. What's the hesitation?\"",
			], [
				["\"It's the money, really.\"", &"walkaway_gap_too_expensive"],
				["\"My insurance covers that, right?\"", &"walkaway_gap_insured"],
				["\"Isn't that what insurance is for?\"", &"walkaway_gap_insured"],
			]],
		"empathize": [[
				"\"No worries. Can I ask why?\"",
				"\"That's fine. Mind if I ask what's behind it?\"",
			], ["\"Just seems unnecessary.\"", "\"Sure.\""]],
	},

	# ---- Everything else: generic, plus a joke per product. No value lines
	# here on purpose - Back to Value falls back to the product's own pitch.
	{"id": &"too_expensive",
		"raise": [&"objection", [
			["\"It's too expensive.\""],
			["\"What's that going to cost me?\""],
			["\"That's a lot of money.\""],
			["\"Yikes. That's pricey.\""],
			["\"Fine. What's the other guy charging for it?\"", [&"hawk"]],
			["\"I'm not paying for that.\"", [&"karen"]],
		]],
		"clarify": [[
				"\"So you like it, it's just the price?\"",
				"\"So the product's fine, it's the cost?\"",
				"\"Is it the monthly, or the total?\"",
			], ["\"Pretty much.\"", "\"Mostly the cost.\"", "\"The monthly, mostly.\""]],
		"empathize": [[
				"\"Totally fair. Nobody wants a bigger payment.\"",
				"\"I get it. Money's tight for everyone.\"",
				"\"Fair. It is an extra cost.\"",
			], ["\"No kidding.\"", "\"Tell me about it.\"", "\"It really is.\""]],
		"budget": [[
				"\"Let me see what I can do on the price.\"",
				"\"Let me see if there's a cheaper way.\"",
				"\"I can probably do better on that.\"",
			], ["\"Now we're talking.\"", "\"Okay, let's see it.\"", "\"Better how?\""]],
		"relate": [[
				"\"That's about three coffees a week.\"",
				"\"It's less than a streaming subscription.\"",
				"\"Think of it as a coffee a week.\"",
			], ["\"I do drink a lot of coffee.\"", "\"Okay, that's not much.\"", "\"Ha. Fine.\""]],
		"close": [["\"If I can make the number work, are we good?\"",
			"\"If the price works, are we good?\"",
			"\"Can I make this fit your budget?\""]],
	},
	{"id": &"dont_need",
		"raise": [&"objection", [
			["\"I don't think I need that.\""],
			["\"Do I look like I need all that?\""],
			["\"I'll take my chances.\""],
			["\"Seems like overkill.\""],
			["\"My cousin's a mechanic. Sort of.\"", [], [&"vsc"]],
			["\"Who would steal THIS car?\"", [], [&"theft"]],
			["\"I'll just wash it more. Probably.\"", [], [&"appearance"]],
			["\"I like waiting rooms. Free coffee.\"", [], [&"concierge"]],
			["\"The heaviest thing I tow is groceries.\"", [], [&"perf"]],
			["\"I'm never getting laid off. I'm the boss's nephew.\"", [], [&"ppp"]],
			["\"I've never missed a payment in my life.\"", [], [&"flex"]],
			["\"I'm driving this until the wheels fall off.\"", [], [&"tvp"]],
			["\"I'm a really good driver, though.\"", [], [&"gap"]],
		]],
		"clarify": [[
				"\"What makes you feel you won't need it?\"",
				"\"Have you ever been caught off guard by a bill?\"",
				"\"What would you do if something did happen?\"",
			], ["\"It's just never come up.\"", "\"Once or twice.\"", "\"Figure it out, I guess.\""]],
		"empathize": [[
				"\"Fair. A lot of people feel that way at first.\"",
				"\"I get it. Feels like one more thing.\"",
				"\"Fair. Not everyone wants extras.\"",
			], ["\"Glad it's not just me.\"", "\"Exactly.\"", "\"Right.\""]],
		"relate": [[
				"\"Nobody needs an umbrella until it rains.\"",
				"\"You insure your phone. Why not the car?\"",
				"\"Like a spare tire. Forgettable, until you need it.\"",
			], ["\"Ha. Okay, okay.\"", "\"Okay, fair.\"", "\"Ha. True.\""]],
		"close": [["\"Can you see how it might be worth having?\"",
			"\"Want it, just in case?\"",
			"\"Shall we add it for peace of mind?\""]],
	},
	{"id": &"no_thanks",
		"raise": [&"objection", [
			["\"No thanks.\""],
			["\"I'll pass.\""],
			["\"Nah, I'm good.\""],
			["\"Not today, thanks.\""],
			["\"No thanks. Are we almost done?\"", [&"kicker"]],
		]],
		"clarify": [[
				"\"Is it the price, or the product?\"",
				"\"Is it the cost, or you don't need it?\"",
			], [
				["\"It's the price.\"", &"too_expensive"],
				["\"The cost.\"", &"too_expensive"],
				["\"I don't think I need it.\"", &"dont_need"],
				["\"I just don't need it.\"", &"dont_need"],
			]],
		"listen": [[
				"\"No pressure. What's holding you back?\"",
				"\"Okay. What's making you hesitate?\"",
			], [
				["\"It's the money, mostly.\"", &"too_expensive"],
				["\"It's the price, honestly.\"", &"too_expensive"],
				["\"I just don't need it.\"", &"dont_need"],
			]],
		"empathize": [[
				"\"No problem at all. Can I ask why?\"",
				"\"That's okay. Mind if I ask why?\"",
			], ["\"Just not sure it's worth it.\"", "\"I just don't see the point.\""]],
	},
]

func _init() -> void:
	DirAccess.make_dir_recursive_absolute(DIR)

	var built: Array[DialogueLine] = []
	for row in LINES:
		built.append(_line(row[0], row[1], row[2], row[3], row[4]))
	for k in range(EXCHANGES.size()):
		built.append_array(_exchange_lines(EXCHANGES[k], k))
	for o in OBJECTIONS:
		built.append_array(_objection_lines(o))

	var pool := DialoguePool.new()
	pool.design_rule = DESIGN_RULE
	pool.known_tags.assign(KNOWN_TAGS)
	pool.known_objections.assign(KNOWN_OBJECTIONS)
	pool.lines = built
	var err := ResourceSaver.save(pool, "%s/dialogue_pool.tres" % DIR)
	if err != OK:
		push_error("failed to save dialogue_pool.tres: %d" % err)
		quit(1)
		return

	print("built %d lines across %d tags and %d objections"
		% [built.size(), KNOWN_TAGS.size(), KNOWN_OBJECTIONS.size()])
	quit(0)


func _line(tags: Array, text: String, archetypes: Array = [], products: Array = [],
		bands: Array = [], objections: Array = [],
		becomes: StringName = &"") -> DialogueLine:
	var l := DialogueLine.new()
	l.tags.assign(tags)
	l.text = text
	l.archetype_ids.assign(archetypes)
	l.product_ids.assign(products)
	l.appeal_bands.assign(bands)
	l.objection_ids.assign(objections)
	l.becomes = becomes
	return l


## One OBJECTIONS entry, as lines: its raises, each opening it, then each
## technique's lines for it and their answers to those.
func _objection_lines(o: Dictionary) -> Array[DialogueLine]:
	var id: StringName = o["id"]
	var out: Array[DialogueLine] = []
	if o.has("raise"):
		var tag: StringName = o["raise"][0]
		for r in o["raise"][1]:
			out.append(_line([tag], r[0], r[1] if r.size() > 1 else [],
				r[2] if r.size() > 2 else [], [], [], id))
	for technique in TECHNIQUES:
		if not o.has(technique):
			continue
		var said: Array = o[technique]
		var yours: StringName = TECHNIQUES[technique][0]
		var theirs: StringName = TECHNIQUES[technique][1]
		for text in said[0]:
			out.append(_line([yours], text, [], [], [], [id]))
		if said.size() < 2 or theirs == &"":
			continue
		for answer in said[1]:
			if answer is Array:
				out.append(_line([theirs], answer[0], [], [], [], [id], answer[1]))
			else:
				out.append(_line([theirs], answer, [], [], [], [id]))
	return out

## One EXCHANGES row, as lines: yours, keyed, and the replies written for it.
func _exchange_lines(x: Array, index: int) -> Array[DialogueLine]:
	var key := StringName("%s_%d" % [x[0], index])
	var yours := _line([x[0]], x[2], x[3])
	yours.key = key
	var out: Array[DialogueLine] = [yours]
	for r in x[4]:
		var reply := _line([x[1]], r[0], r[1] if r.size() > 1 else [])
		reply.replies_to.assign([key])
		out.append(reply)
	return out
